import Mathlib

/-!
# Folder 133: the centre and the derived group seen from two crossed modules

The finding `133-centre-and-derived-group-from-two-crossed-modules` reads in the
modernised reading `transcripts/133/133.modern.tex`, section VII (manuscript
pages 45–53, the leaves « Fourbis auxiliaires cohomologiques pour groupes
formels »):

> Let `G` be a group and `N ⊃ D(G)`, `N′ ⊂ Cent(G)` two normal subgroups, so
> that `N → M = G/N′` and `N′ → M′ = G/N` are crossed modules with
> `π₁ = N ∩ N′` and `π₀ = G/NN′`. Then `N′ = Cent(G)` iff a map
> `Ψ_G : ℨ → Hom(π₀, π₁)` is injective (page 46), and `N = D(G)` iff an
> alternating pairing `λ_G : π₀ ⊗ π₀ → (N_ab)_M` is surjective (pages 51–52).

Everything here is for abstract groups (the page works in a topos; nothing
in these two statements uses more than group theory). Proving the claim says
only that it holds as stated; whether it is in the literature is not touched.

## 1. Page 46: `N′ = Cent(G) ⇔ Ψ_G injective`

`K = G/π₁`, and `ℨ = [Cent(K)/(N′/π₁)] ∩ Ker Θ` is taken through its inverse
image `zbar N N'` in `G`: the elements whose image in `K` is central and which
centralise `N` (`Ker Θ`, `Θ : M → Aut N` being conjugation). Then
`ℨ = zbar ⧸ N′`. For `z ∈ zbar` the commutator `g ↦ ⁅g, z⁆` takes values in
`π₁`, is a homomorphism in `g` and kills `N` and `N′` (`commHom`), hence
factors through `π₀` (`phi`); it depends only on the class of `z` modulo `N′`,
which defines `Psi : ℨ → (π₀ →* π₁)`, multiplicative in `z` (`Psi_mul`).
`injective_Psi_iff` is the boxed equivalence of page 46. Only `N′ ⊂ Cent(G)`
is used — the hypothesis `[N, N′] = 1` that the reading adds follows from it,
and `N ⊃ D(G)` plays no role here.

## 2. Pages 51–52: `N = D(G) ⇔ λ_G surjective`

`𝒟 = (N_ab)_M`, the coinvariants under `M` of the abelianised `N`, is
`N ⧸ ⁅G, N⁆`: the kernel `N₀` of `N → 𝒟` is generated by the `⁅g, n⁆`, which
contain the `⁅n, n'⁆`. With `D(G) ⊂ N` (so that `π₀` is commutative,
`pi0_comm`) and `N′` central, `⁅x, y⁆ ↦ [⁅x, y⁆]` descends to a pairing
`lam : π₀ → π₀ → 𝒟`, multiplicative in each variable and alternating
(`lam_mul_left`, `lam_mul_right`, `lam_self`, `lam_swap`). The image of the
linear map `π₀ ⊗ π₀ → 𝒟` it induces is the subgroup generated by its values,
so « `λ_G` surjective » is `closure (range lam) = ⊤`;
`eq_commutator_iff_lam_surjective` proves the equivalence with `N = D(G)`.
The centrality of `N′` is needed for `lam` to be defined on `π₀`.

## 3. Pages 48 and 52: changing `G` by a central extension `E`

`G₁ = (G ×_{π₀} E)/π₁`. `fibre` is the fibre product, `G1` its quotient by the
antidiagonal image of `π₁`. `commutator_G1` is the computation behind
`Ψ_{G₁} = Ψ_G + c̃_E α` and `λ_{G₁} = λ_G + β c_E`: in `G₁` the commutator of
two classes is the class of the commutator in `G` multiplied by the value of
the commutator pairing `c_E` of `E`; `cE_well_defined` shows that `c_E`
depends only on the images in `π₀`. `Psi_G1` reads this for `z ∈ zbar` as
`Ψ_G(z̄)(ḡ) · c_E(e, f)`, and `lam_G1` reads the class in `𝒟` as
`λ_G(x̄, ȳ) · β(c)`. `E` is given by `ι : π₁ → E` with central image and
`q : E → π₀` with `Ker q = ι(π₁)`; the surjectivity of `q` is not used. The
identification of the two crossed modules of `G₁` with those of `G`, which
would make these equalities of elements into equalities of maps on one and
the same `ℨ`, is not formalised.
-/

namespace Grothendieck.Folder133

open Subgroup
open scoped commutatorElement

variable {G : Type*} [Group G] (N N' : Subgroup G) [N.Normal] [N'.Normal]

/-! ### Page 46 -/

/-- The inverse image in `G` of `ℨ = [Cent(K)/(N′/π₁)] ∩ Ker Θ`, `K = G/π₁`,
`π₁ = N ∩ N′` (page 46): the elements central modulo `π₁` that centralise `N`. -/
def zbar : Subgroup G :=
  (center (G ⧸ (N ⊓ N'))).comap (QuotientGroup.mk' (N ⊓ N')) ⊓ centralizer (N : Set G)

/-- `ℨ = zbar ⧸ N′` (page 46). -/
abbrev Zfrak := zbar N N' ⧸ N'.subgroupOf (zbar N N')

variable {N N'}

theorem mem_zbar {z : G} :
    z ∈ zbar N N' ↔ (∀ g : G, ⁅g, z⁆ ∈ N ⊓ N') ∧ ∀ n ∈ N, n * z = z * n := by
  rw [zbar, mem_inf, mem_comap, mem_centralizer_iff]
  refine and_congr ⟨fun h g => ?_, fun h => mem_center_iff.mpr fun x => ?_⟩ Iff.rfl
  · rw [← QuotientGroup.eq_one_iff]
    show QuotientGroup.mk' (N ⊓ N') ⁅g, z⁆ = 1
    rw [map_commutatorElement]
    exact commutatorElement_eq_one_iff_mul_comm.mpr (mem_center_iff.mp h _)
  · obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective x
    have := h g
    rw [← QuotientGroup.eq_one_iff] at this
    change QuotientGroup.mk' (N ⊓ N') ⁅g, z⁆ = 1 at this
    rw [map_commutatorElement] at this
    exact commutatorElement_eq_one_iff_mul_comm.mp this

/-- A central element commutes with everything, written in the order used below. -/
private theorem central_comm {H : Type*} [Group H] {c : H} (hc : c ∈ center H) (x : H) :
    c * x = x * c :=
  (mem_center_iff.mp hc x).symm

/-- Multiplying the second argument of a commutator by a central element does not change it. -/
private theorem comm_mul_central {H : Type*} [Group H] {c : H} (hc : c ∈ center H) (g z : H) :
    ⁅g, z * c⁆ = ⁅g, z⁆ := by
  simp only [commutatorElement_def]
  calc g * (z * c) * g⁻¹ * (z * c)⁻¹ = g * z * (c * g⁻¹) * c⁻¹ * z⁻¹ := by group
    _ = g * z * (g⁻¹ * c) * c⁻¹ * z⁻¹ := by rw [central_comm hc]
    _ = g * z * g⁻¹ * z⁻¹ := by group

/-- Multiplying the first argument of a commutator by a central element does not change it. -/
private theorem comm_mul_central_left {H : Type*} [Group H] {c : H} (hc : c ∈ center H)
    (g z : H) : ⁅g * c, z⁆ = ⁅g, z⁆ := by
  rw [← commutatorElement_inv, comm_mul_central hc, commutatorElement_inv]

section Centre

variable (hN' : N' ≤ center G)
include hN'

theorem comm_mem_center {z : G} (hz : z ∈ zbar N N') (g : G) : ⁅g, z⁆ ∈ center G :=
  hN' (mem_inf.mp ((mem_zbar.mp hz).1 g)).2

theorem comm_mul_left {z : G} (hz : z ∈ zbar N N') (g h : G) :
    ⁅g * h, z⁆ = ⁅g, z⁆ * ⁅h, z⁆ := by
  have hc := comm_mem_center hN' hz h
  calc ⁅g * h, z⁆ = g * (⁅h, z⁆ * (z * g⁻¹ * z⁻¹)) := by
        simp only [commutatorElement_def]; group
    _ = ⁅h, z⁆ * (g * z * g⁻¹ * z⁻¹) := by
        rw [← mul_assoc, ← central_comm hc g]; group
    _ = ⁅h, z⁆ * ⁅g, z⁆ := by rw [commutatorElement_def g z]
    _ = ⁅g, z⁆ * ⁅h, z⁆ := central_comm hc _

/-- For `z ∈ zbar`, `g ↦ ⁅g, z⁆` as a homomorphism `G →* π₁`. -/
def commHom (z : zbar N N') : G →* ↥(N ⊓ N') where
  toFun g := ⟨⁅g, z⁆, (mem_zbar.mp z.2).1 g⟩
  map_one' := by ext; simp
  map_mul' g h := by ext; exact comm_mul_left hN' z.2 g h

theorem le_ker_commHom (z : zbar N N') : N ⊔ N' ≤ (commHom hN' z).ker := by
  refine sup_le (fun n hn => ?_) (fun n hn => ?_) <;> rw [MonoidHom.mem_ker] <;>
    apply Subtype.ext <;> show ⁅n, (z : G)⁆ = 1 <;> rw [commutatorElement_eq_one_iff_mul_comm]
  · exact (mem_zbar.mp z.2).2 n hn
  · exact (mem_center_iff.mp (hN' hn) z).symm

/-- `φ_G(z) : π₀ → π₁`, `π₀ = G/NN′`: the commutator with `z`, on `π₀`. -/
def phi (z : zbar N N') : G ⧸ (N ⊔ N') →* ↥(N ⊓ N') :=
  QuotientGroup.lift _ (commHom hN' z) (le_ker_commHom hN' z)

theorem phi_mk (z : zbar N N') (g : G) :
    (phi hN' z (g : G ⧸ (N ⊔ N')) : G) = ⁅g, (z : G)⁆ := rfl

theorem phi_eq_of_rel {z w : zbar N N'} (h : z⁻¹ * w ∈ N'.subgroupOf (zbar N N')) :
    phi hN' z = phi hN' w := by
  apply QuotientGroup.monoidHom_ext
  apply MonoidHom.ext
  intro g
  apply Subtype.ext
  show ⁅g, (z : G)⁆ = ⁅g, (w : G)⁆
  have hc : (z : G)⁻¹ * w ∈ center G := hN' (by simpa [mem_subgroupOf] using h)
  have : (w : G) = z * ((z : G)⁻¹ * w) := by group
  rw [this, comm_mul_central hc]

/-- `Ψ_G : ℨ → Hom(π₀, π₁)` (page 46). -/
def Psi : Zfrak N N' → (G ⧸ (N ⊔ N') →* ↥(N ⊓ N')) :=
  fun a => Quotient.liftOn' a (phi hN') fun _ _ h =>
    phi_eq_of_rel hN' (QuotientGroup.leftRel_apply.mp h)

theorem Psi_mk (z : zbar N N') (g : G) :
    (Psi hN' (z : Zfrak N N') (g : G ⧸ (N ⊔ N')) : G) = ⁅g, (z : G)⁆ := rfl

/-- `Ψ_G` is a homomorphism: `Ψ_G(ab) = Ψ_G(a) Ψ_G(b)` pointwise. -/
theorem Psi_mul (a b : Zfrak N N') (x : G ⧸ (N ⊔ N')) :
    Psi hN' (a * b) x = Psi hN' a x * Psi hN' b x := by
  induction a using QuotientGroup.induction_on with | H z => ?_
  induction b using QuotientGroup.induction_on with | H w => ?_
  induction x using QuotientGroup.induction_on with | H g => ?_
  apply Subtype.ext
  show ⁅g, ((z * w : zbar N N') : G)⁆ = ⁅g, (z : G)⁆ * ⁅g, (w : G)⁆
  rw [coe_mul]
  have hw := comm_mem_center hN' w.2 g
  calc ⁅g, (z : G) * w⁆ = g * z * g⁻¹ * (⁅g, (w : G)⁆ * (z : G)⁻¹) := by
        simp only [commutatorElement_def]; group
    _ = g * z * g⁻¹ * ((z : G)⁻¹ * ⁅g, (w : G)⁆) := by rw [central_comm hw]
    _ = ⁅g, (z : G)⁆ * ⁅g, (w : G)⁆ := by rw [commutatorElement_def g (z : G)]; group

/-- **Page 46.** `N′ = Cent(G)` if and only if `Ψ_G` is injective. -/
theorem injective_Psi_iff : Function.Injective (Psi (N := N) hN') ↔ N' = center G := by
  constructor
  · intro hinj
    refine le_antisymm hN' fun c hc => ?_
    have hcz : c ∈ zbar N N' := mem_zbar.mpr ⟨fun g => by
      rw [commutatorElement_eq_one_iff_mul_comm.mpr (mem_center_iff.mp hc g)]
      exact one_mem _, fun n _ => mem_center_iff.mp hc n⟩
    have : Psi hN' ((⟨c, hcz⟩ : zbar N N') : Zfrak N N') =
        Psi hN' ((1 : zbar N N') : Zfrak N N') := by
      apply QuotientGroup.monoidHom_ext
      apply MonoidHom.ext
      intro g
      apply Subtype.ext
      show ⁅g, c⁆ = ⁅g, ((1 : zbar N N') : G)⁆
      rw [commutatorElement_eq_one_iff_mul_comm.mpr (mem_center_iff.mp hc g)]
      simp
    have h1 := hinj this
    rw [QuotientGroup.eq] at h1
    simpa [mem_subgroupOf] using h1
  · intro hc a b hab
    induction a using QuotientGroup.induction_on with | H z => ?_
    induction b using QuotientGroup.induction_on with | H w => ?_
    rw [QuotientGroup.eq, mem_subgroupOf]
    apply le_of_eq hc.symm
    have key : ∀ g : G, ⁅g, (z : G)⁆ = ⁅g, (w : G)⁆ := fun g =>
      congrArg (fun f => (f (g : G ⧸ (N ⊔ N')) : G)) hab
    refine mem_center_iff.mpr fun g => ?_
    have h3 := key g⁻¹
    rw [commutatorElement_def, commutatorElement_def, inv_inv] at h3
    have e : (z : G) * g * (z : G)⁻¹ = w * g * (w : G)⁻¹ := by
      calc (z : G) * g * (z : G)⁻¹ = g * (g⁻¹ * z * g * (z : G)⁻¹) := by group
        _ = g * (g⁻¹ * w * g * (w : G)⁻¹) := by rw [h3]
        _ = w * g * (w : G)⁻¹ := by group
    rw [coe_mul, coe_inv]
    calc g * ((z : G)⁻¹ * w) = (z : G)⁻¹ * ((z : G) * g * (z : G)⁻¹) * w := by group
      _ = (z : G)⁻¹ * (w * g * (w : G)⁻¹) * w := by rw [e]
      _ = (z : G)⁻¹ * w * g := by group

end Centre

/-! ### Pages 51–52 -/

section Derived

/-- `𝒟 = (N_ab)_M`, the coinvariants under `M = G/N′` of the abelianised `N`
(page 51): the quotient of `N` by `⁅G, N⁆`. -/
abbrev Dcal (N : Subgroup G) [N.Normal] := ↥N ⧸ (⁅(⊤ : Subgroup G), N⁆).subgroupOf N

/-- The class in `𝒟` of an element of `N`. -/
def dmk (n : G) (hn : n ∈ N) : Dcal N := ((⟨n, hn⟩ : N) : Dcal N)

theorem dmk_eq_one_iff {n : G} (hn : n ∈ N) : dmk n hn = 1 ↔ n ∈ ⁅(⊤ : Subgroup G), N⁆ := by
  rw [dmk, QuotientGroup.eq_one_iff, mem_subgroupOf]

theorem dmk_eq_iff {a b : G} (ha : a ∈ N) (hb : b ∈ N) :
    dmk a ha = dmk b hb ↔ a⁻¹ * b ∈ ⁅(⊤ : Subgroup G), N⁆ := by
  rw [dmk, dmk, QuotientGroup.eq, mem_subgroupOf, coe_mul, coe_inv]

theorem dmk_eq_of_eq {a b : G} (h : a = b) (ha : a ∈ N) (hb : b ∈ N) : dmk a ha = dmk b hb := by
  subst h; rfl

theorem dmk_mul {a b : G} (ha : a ∈ N) (hb : b ∈ N) :
    dmk (a * b) (mul_mem ha hb) = dmk a ha * dmk b hb := rfl

theorem dmk_inv {a : G} (ha : a ∈ N) : dmk a⁻¹ (inv_mem ha) = (dmk a ha)⁻¹ := rfl

theorem dmk_one : dmk (1 : G) (one_mem N) = 1 := rfl

/-- `G` acts trivially on `𝒟`. -/
theorem dmk_conj {c : G} (hc : c ∈ N) (x : G) :
    dmk (x * c * x⁻¹) (‹N.Normal›.conj_mem c hc x) = dmk c hc := by
  rw [dmk_eq_iff]
  have : (x * c * x⁻¹)⁻¹ * c = ⁅x, c⁻¹⁆ := by simp only [commutatorElement_def]; group
  rw [this]
  exact commutator_mem_commutator (mem_top x) (inv_mem hc)

/-- `𝒟` is commutative. -/
theorem dmk_comm {a b : G} (ha : a ∈ N) (hb : b ∈ N) : dmk a ha * dmk b hb = dmk b hb * dmk a ha := by
  rw [← dmk_mul, ← dmk_mul, dmk_eq_iff]
  have : (a * b)⁻¹ * (b * a) = ⁅b⁻¹, a⁻¹⁆ := by simp only [commutatorElement_def]; group
  rw [this]
  exact commutator_mem_commutator (mem_top _) (inv_mem ha)

theorem Dcal_comm (u v : Dcal N) : u * v = v * u := by
  induction u using QuotientGroup.induction_on with | H a => ?_
  induction v using QuotientGroup.induction_on with | H b => ?_
  exact dmk_comm a.2 b.2

omit [N.Normal] in
theorem comm_mem (hD : _root_.commutator G ≤ N) (x y : G) : ⁅x, y⁆ ∈ N :=
  hD (commutator_mem_commutator (mem_top x) (mem_top y))

/-- `π₀ = G/NN′` is commutative as soon as `N ⊃ D(G)`. -/
theorem pi0_comm (hD : _root_.commutator G ≤ N) (a b : G ⧸ (N ⊔ N')) : a * b = b * a := by
  induction a using QuotientGroup.induction_on with | H x => ?_
  induction b using QuotientGroup.induction_on with | H y => ?_
  rw [← QuotientGroup.mk_mul, ← QuotientGroup.mk_mul, QuotientGroup.eq]
  have : (x * y)⁻¹ * (y * x) = ⁅y⁻¹, x⁻¹⁆ := by simp only [commutatorElement_def]; group
  rw [this]
  exact mem_sup_left (comm_mem hD _ _)

/-- For fixed `y`, `x ↦ [⁅x, y⁆] ∈ 𝒟` is a homomorphism. -/
def lamG (hD : _root_.commutator G ≤ N) (y : G) : G →* Dcal N where
  toFun x := dmk ⁅x, y⁆ (comm_mem hD x y)
  map_one' := by
    rw [← dmk_one]
    exact dmk_eq_of_eq (commutatorElement_one_left y) _ _
  map_mul' x x' := by
    have e : ⁅x * x', y⁆ = (x * ⁅x', y⁆ * x⁻¹) * ⁅x, y⁆ := by
      simp only [commutatorElement_def]; group
    have hconj := ‹N.Normal›.conj_mem _ (comm_mem hD x' y) x
    rw [dmk_eq_of_eq e _ (mul_mem hconj (comm_mem hD x y)), dmk_mul hconj (comm_mem hD x y),
      dmk_conj, dmk_comm]

variable (hD : _root_.commutator G ≤ N)

theorem lamG_apply (y x : G) : lamG hD y x = dmk ⁅x, y⁆ (comm_mem hD x y) := rfl

omit [N'.Normal] in
theorem le_ker_lamG (hN' : N' ≤ center G) (y : G) : N ⊔ N' ≤ (lamG hD y).ker := by
  refine sup_le (fun n hn => ?_) (fun n hn => ?_) <;> rw [MonoidHom.mem_ker, lamG_apply,
    dmk_eq_one_iff]
  · rw [← commutatorElement_inv]
    exact inv_mem (commutator_mem_commutator (mem_top y) hn)
  · rw [commutatorElement_eq_one_iff_mul_comm.mpr (mem_center_iff.mp (hN' hn) y).symm]
    exact one_mem _

omit [N'.Normal] in
theorem lamG_eq_of_rel (hN' : N' ≤ center G) (y : G) {x x' : G} (h : x⁻¹ * x' ∈ N ⊔ N') :
    lamG hD y x = lamG hD y x' := by
  have : x' = x * (x⁻¹ * x') := by group
  rw [this, map_mul, le_ker_lamG hD hN' y h, mul_one]

theorem lamG_swap (x y : G) : lamG hD y x = (lamG hD x y)⁻¹ := by
  rw [lamG_apply, lamG_apply, ← dmk_inv]
  exact dmk_eq_of_eq (commutatorElement_inv y x).symm _ _

/-- `λ_G : π₀ × π₀ → 𝒟`, the commutator of two lifts (page 51). -/
def lam (hN' : N' ≤ center G) : G ⧸ (N ⊔ N') → G ⧸ (N ⊔ N') → Dcal N :=
  fun a b => Quotient.liftOn₂' a b (fun x y => lamG hD y x) fun x y x' y' hx hy => by
    show lamG hD y x = lamG hD y' x'
    rw [lamG_eq_of_rel hD hN' y (QuotientGroup.leftRel_apply.mp hx), lamG_swap hD x' y,
      lamG_eq_of_rel hD hN' x' (QuotientGroup.leftRel_apply.mp hy), ← lamG_swap hD x' y']

variable (hN' : N' ≤ center G)

omit [N'.Normal] in
theorem lam_mk (x y : G) :
    lam hD hN' (x : G ⧸ (N ⊔ N')) (y : G ⧸ (N ⊔ N')) = dmk ⁅x, y⁆ (comm_mem hD x y) := rfl

theorem lam_mul_left (a a' b : G ⧸ (N ⊔ N')) :
    lam hD hN' (a * a') b = lam hD hN' a b * lam hD hN' a' b := by
  induction a using QuotientGroup.induction_on with | H x => ?_
  induction a' using QuotientGroup.induction_on with | H x' => ?_
  induction b using QuotientGroup.induction_on with | H y => ?_
  exact map_mul (lamG hD y) x x'

omit [N'.Normal] in
theorem lam_swap (a b : G ⧸ (N ⊔ N')) : lam hD hN' a b = (lam hD hN' b a)⁻¹ := by
  induction a using QuotientGroup.induction_on with | H x => ?_
  induction b using QuotientGroup.induction_on with | H y => ?_
  exact lamG_swap hD x y

theorem lam_mul_right (a b b' : G ⧸ (N ⊔ N')) :
    lam hD hN' a (b * b') = lam hD hN' a b * lam hD hN' a b' := by
  rw [lam_swap hD hN' a (b * b'), lam_mul_left, mul_inv_rev, ← lam_swap, ← lam_swap, Dcal_comm]

omit [N'.Normal] in
/-- `λ_G` is alternating. -/
theorem lam_self (a : G ⧸ (N ⊔ N')) : lam hD hN' a a = 1 := by
  induction a using QuotientGroup.induction_on with | H x => ?_
  rw [lam_mk, ← dmk_one]
  exact dmk_eq_of_eq (commutatorElement_self x) _ _

omit [N'.Normal] in
/-- **Pages 51–52.** With `N ⊃ D(G)` and `N′ ⊂ Cent(G)`, `N = D(G)` if and only if
`λ_G` is surjective, i.e. its values generate `𝒟`. -/
theorem eq_commutator_iff_lam_surjective :
    N = _root_.commutator G ↔
      closure (Set.range fun p : (G ⧸ (N ⊔ N')) × (G ⧸ (N ⊔ N')) => lam hD hN' p.1 p.2) = ⊤ := by
  have hcl : closure (commutatorSet G) ≤ N := by rw [← commutator_eq_closure]; exact hD
  constructor
  · intro h
    rw [eq_top_iff]
    intro u _
    induction u using QuotientGroup.induction_on with | H a => ?_
    obtain ⟨n, hn⟩ := a
    have hn' : n ∈ closure (commutatorSet G) := by rw [← commutator_eq_closure, ← h]; exact hn
    have key : ∀ (m : G) (hm : m ∈ closure (commutatorSet G)), dmk m (hcl hm) ∈
        closure (Set.range fun p : (G ⧸ (N ⊔ N')) × (G ⧸ (N ⊔ N')) => lam hD hN' p.1 p.2) := by
      intro m hm
      induction hm using closure_induction with
      | mem x hx =>
        obtain ⟨a, b, rfl⟩ := mem_commutatorSet_iff.mp hx
        exact subset_closure ⟨((a : G ⧸ (N ⊔ N')), (b : G ⧸ (N ⊔ N'))), rfl⟩
      | one => exact one_mem _
      | mul x y hx hy ihx ihy =>
        have := mul_mem ihx ihy
        rwa [← dmk_mul] at this
      | inv x hx ihx =>
        have := inv_mem ihx
        rwa [← dmk_inv] at this
    exact key n hn'
  · intro hS
    refine le_antisymm (fun n hn => ?_) hD
    have hT : closure (Set.range fun p : (G ⧸ (N ⊔ N')) × (G ⧸ (N ⊔ N')) => lam hD hN' p.1 p.2) ≤
        ((_root_.commutator G).subgroupOf N).map (QuotientGroup.mk' _) := by
      rw [closure_le]
      rintro _ ⟨⟨a, b⟩, rfl⟩
      obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective a
      obtain ⟨y, rfl⟩ := QuotientGroup.mk_surjective b
      exact ⟨⟨⁅x, y⁆, comm_mem hD x y⟩,
        mem_subgroupOf.mpr (commutator_mem_commutator (mem_top x) (mem_top y)), rfl⟩
    have := hT (by rw [hS]; exact mem_top (dmk n hn))
    obtain ⟨m, hm, hmn⟩ := mem_map.mp this
    rw [QuotientGroup.mk'_apply] at hmn
    have h1 := QuotientGroup.eq.mp hmn
    rw [mem_subgroupOf] at hm h1
    have h2 : (m : G)⁻¹ * n ∈ _root_.commutator G :=
      commutator_mono le_top le_top (by simpa using h1)
    have : n = (m : G) * ((m : G)⁻¹ * n) := by group
    rw [this]
    exact mul_mem hm h2

end Derived

/-! ### Pages 48 and 52: a central extension `E` of `π₀` by `π₁` -/

section Extension

variable (hD : _root_.commutator G ≤ N) (hN' : N' ≤ center G)
variable {E : Type*} [Group E] (ι : ↥(N ⊓ N') →* E) (q : E →* G ⧸ (N ⊔ N'))

/-- The fibre product `G ×_{π₀} E`. -/
def fibre : Subgroup (G × E) :=
  ((QuotientGroup.mk' (N ⊔ N')).comp (MonoidHom.fst G E)).eqLocus (q.comp (MonoidHom.snd G E))

/-- `π₁` embedded antidiagonally in the fibre product (`ι` lands in `Ker q`). -/
def antidiag (hex : q.ker = ι.range) (a : ↥(N ⊓ N')) : fibre q :=
  ⟨((a : G), (ι a)⁻¹), by
    have h1 : ((a : G) : G ⧸ (N ⊔ N')) = 1 :=
      (QuotientGroup.eq_one_iff _).mpr (mem_sup_left (mem_inf.mp a.2).1)
    have h2 : q (ι a)⁻¹ = 1 := by
      rw [map_inv, inv_eq_one, ← MonoidHom.mem_ker, hex]; exact ⟨a, rfl⟩
    change ((a : G) : G ⧸ (N ⊔ N')) = q (ι a)⁻¹
    rw [h1, h2]⟩

/-- `G₁ = (G ×_{π₀} E)/π₁`. The antidiagonal image of `π₁` is central, so its
normal closure is itself; the normal closure is taken only to have a quotient group
without carrying that proof in the type. -/
abbrev G1 (hex : q.ker = ι.range) := fibre q ⧸ normalClosure (Set.range (antidiag ι q hex))

/-- `N ⊂ G` seen in the fibre product, as `n ↦ (n, 1)`. -/
def incN {n : G} (hn : n ∈ N) : fibre q :=
  ⟨(n, 1), by
    change ((n : G) : G ⧸ (N ⊔ N')) = q 1
    rw [map_one, QuotientGroup.eq_one_iff]
    exact mem_sup_left hn⟩

theorem incN_coe {n : G} (hn : n ∈ N) : (incN q hn : G × E) = (n, 1) := rfl

theorem antidiag_coe (hex : q.ker = ι.range) (a : ↥(N ⊓ N')) :
    (antidiag ι q hex a : G × E) = ((a : G), (ι a)⁻¹) := rfl

include hD in
/-- The commutator of two elements of `E` lies in `ι(π₁)` when `π₀` is commutative. -/
theorem comm_mem_range (hex : q.ker = ι.range) (e f : E) : ⁅e, f⁆ ∈ ι.range := by
  rw [← hex, MonoidHom.mem_ker, map_commutatorElement, commutatorElement_eq_one_iff_mul_comm]
  exact pi0_comm hD _ _

/-- The commutator pairing of `E`: `ι (c_E e f) = ⁅e, f⁆` (page 48). -/
noncomputable def cE (hex : q.ker = ι.range) (e f : E) : ↥(N ⊓ N') :=
  (MonoidHom.mem_range.mp (comm_mem_range hD ι q hex e f)).choose

theorem cE_spec (hex : q.ker = ι.range) (e f : E) : ι (cE hD ι q hex e f) = ⁅e, f⁆ :=
  (MonoidHom.mem_range.mp (comm_mem_range hD ι q hex e f)).choose_spec

/-- `c_E` depends only on the images in `π₀`: it is a pairing `π₀ × π₀ → π₁`. -/
theorem cE_well_defined (hex : q.ker = ι.range) (hιc : ∀ a, ι a ∈ center E)
    (hι : Function.Injective ι) {e e' f f' : E} (he : q e = q e') (hf : q f = q f') :
    cE hD ι q hex e f = cE hD ι q hex e' f' := by
  apply hι
  rw [cE_spec, cE_spec]
  have ke : e⁻¹ * e' ∈ ι.range := by rw [← hex, MonoidHom.mem_ker, map_mul, map_inv, he,
    inv_mul_cancel]
  have kf : f⁻¹ * f' ∈ ι.range := by rw [← hex, MonoidHom.mem_ker, map_mul, map_inv, hf,
    inv_mul_cancel]
  obtain ⟨a, ha⟩ := ke
  obtain ⟨b, hb⟩ := kf
  have e1 : e' = e * ι a := by rw [ha]; group
  have f1 : f' = f * ι b := by rw [hb]; group
  rw [e1, f1, comm_mul_central_left (hιc a), comm_mul_central (hιc b)]

/-- **Pages 48 and 52.** In `G₁`, the commutator of the classes of `(g, e)` and
`(z, f)` is the class of `(⁅g, z⁆ · c_E(e, f), 1)`: the commutator in `G` times
the commutator pairing of `E`. -/
theorem commutator_G1 (hex : q.ker = ι.range) (p r : fibre q) :
    (⁅(p : G1 ι q hex), (r : G1 ι q hex)⁆ : G1 ι q hex) =
      ((incN q (mul_mem (comm_mem hD (p : G × E).1 (r : G × E).1)
        (mem_inf.mp (cE hD ι q hex (p : G × E).2 (r : G × E).2).2).1) : fibre q) : G1 ι q hex) := by
  have hm : (⁅(p : G1 ι q hex), (r : G1 ι q hex)⁆ : G1 ι q hex) =
      ((⁅p, r⁆ : fibre q) : G1 ι q hex) :=
    (map_commutatorElement (QuotientGroup.mk' (normalClosure (Set.range (antidiag ι q hex))))
      p r).symm
  have hpr : ((⁅p, r⁆ : fibre q) : G × E) =
      (⁅(p : G × E).1, (r : G × E).1⁆, ⁅(p : G × E).2, (r : G × E).2⁆) :=
    Prod.ext (by simp [commutatorElement_def]) (by simp [commutatorElement_def])
  rw [hm, QuotientGroup.eq]
  apply subset_normalClosure
  refine ⟨cE hD ι q hex (p : G × E).2 (r : G × E).2, ?_⟩
  have hc := cE_spec hD ι q hex (p : G × E).2 (r : G × E).2
  apply Subtype.ext
  rw [coe_mul, coe_inv, hpr, incN_coe, antidiag_coe]
  refine Prod.ext ?_ ?_
  · simp only [Prod.fst_mul, Prod.fst_inv, inv_mul_cancel_left]
  · simp only [Prod.snd_mul, Prod.snd_inv, mul_one, hc]

/-- **Page 48.** `Ψ_{G₁} = Ψ_G · c̃_E α`: for `z ∈ zbar`, the commutator in `G₁` of
the classes of `(g, e)` and `(z, f)` is the image of `Ψ_G(z)(ḡ) · c_E(e, f) ∈ π₁`. -/
theorem Psi_G1 (hex : q.ker = ι.range) (p r : fibre q) (hz : (r : G × E).1 ∈ zbar N N') :
    (⁅(p : G1 ι q hex), (r : G1 ι q hex)⁆ : G1 ι q hex) =
      ((incN q (mem_inf.mp ((Psi hN' ((⟨_, hz⟩ : zbar N N') : Zfrak N N')
        ((p : G × E).1 : G ⧸ (N ⊔ N'))) * cE hD ι q hex (p : G × E).2 (r : G × E).2).2).1
          : fibre q) : G1 ι q hex) :=
  commutator_G1 hD ι q hex p r

omit [N'.Normal] in
/-- **Page 52.** `λ_{G₁} = λ_G + β c_E`: the class in `𝒟` of the element of `N`
given by `commutator_G1` is `λ_G(x̄, ȳ) · β(c_E(e, f))`, `β : π₁ → 𝒟`. -/
theorem lam_G1 (x y : G) (c : ↥(N ⊓ N')) :
    dmk (⁅x, y⁆ * c) (mul_mem (comm_mem hD x y) (mem_inf.mp c.2).1) =
      lam hD hN' (x : G ⧸ (N ⊔ N')) (y : G ⧸ (N ⊔ N')) * dmk (c : G) (mem_inf.mp c.2).1 := rfl

end Extension

end Grothendieck.Folder133
