// Generated by `npm run catalogue` — do not edit by hand.
// Source: https://grothendieck.umontpellier.fr/archives-grothendieck/
// 178 folders, 22 groups, 16074 leaves announced.

import type { ArchiveGroup, Cote } from '../lib/types.ts';

export const GROUPS: ArchiveGroup[] = [
  {
    "id": "1-162",
    "title": "MATHÉMATIQUES / RECHERCHE / Travaux",
    "date": "",
    "cotes": [
      "1",
      "2"
    ]
  },
  {
    "id": "4-9",
    "title": "Cristaux",
    "date": "[à partir de 1958- vers 1971]",
    "cotes": [
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  {
    "id": "10-18",
    "title": "Théorie des motifs",
    "date": "[à partir de 1958-à partir de 1982]",
    "cotes": [
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "18",
      "19"
    ]
  },
  {
    "id": "21-26",
    "title": "Éléments de Géométrie Algébrique (EGA)",
    "date": "[vers 1960-1992]",
    "cotes": [
      "21",
      "22",
      "23",
      "24",
      "25",
      "26"
    ]
  },
  {
    "id": "27-38",
    "title": "Séminaire de Géométrie Algébrique (SGA)",
    "date": "1959-1977",
    "cotes": [
      "27",
      "28",
      "29",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "39",
      "40",
      "41",
      "42"
    ]
  },
  {
    "id": "43-44",
    "title": "Jacobiennes",
    "date": "[à partir de 1961-à partir de 1967]",
    "cotes": [
      "43",
      "44"
    ]
  },
  {
    "id": "45-54",
    "title": "Variétés abéliennes",
    "date": "1961-1973",
    "cotes": [
      "45",
      "46",
      "47",
      "48",
      "49",
      "50",
      "51",
      "52",
      "53",
      "54",
      "55",
      "56"
    ]
  },
  {
    "id": "57-59",
    "title": "Picard",
    "date": "1962-[années 1970]",
    "cotes": [
      "57",
      "58",
      "59",
      "60"
    ]
  },
  {
    "id": "62-64",
    "title": "Courbes elliptiques",
    "date": "[à partir de 1963- 1982]",
    "cotes": [
      "62",
      "63",
      "64"
    ]
  },
  {
    "id": "66-89",
    "title": "Autour de l’enseignement - Thèmes liés (cours et directions de recherches)",
    "date": "1964-1984",
    "cotes": [
      "66",
      "67",
      "68"
    ]
  },
  {
    "id": "69-89",
    "title": "Géométrie et topologie combinatoire",
    "date": "1976-[vers 1986]",
    "cotes": [
      "69",
      "70",
      "71",
      "72",
      "73",
      "74",
      "75",
      "76",
      "77",
      "78",
      "79",
      "80",
      "81",
      "82",
      "83",
      "84",
      "85",
      "86",
      "87",
      "88",
      "89",
      "90",
      "91",
      "93",
      "94",
      "97",
      "98",
      "100",
      "101",
      "102"
    ]
  },
  {
    "id": "103-118",
    "title": "Autour de Pursuing stacks",
    "date": "1968-1984",
    "cotes": [
      "103",
      "104",
      "105",
      "106",
      "107",
      "108",
      "109",
      "111",
      "112",
      "113",
      "114",
      "115",
      "116",
      "117",
      "118"
    ]
  },
  {
    "id": "119-121",
    "title": "Autour d’Esquisse d’un programme",
    "date": "1968-1991",
    "cotes": [
      "119",
      "120",
      "121",
      "122",
      "123",
      "125"
    ]
  },
  {
    "id": "126-128",
    "title": "Descentes",
    "date": "[avant 1970]",
    "cotes": [
      "126",
      "127",
      "128",
      "129",
      "130",
      "131",
      "132",
      "133"
    ]
  },
  {
    "id": "134-1-8",
    "title": "Pursuing stacks (À la poursuite des champs). First episode : The Modelizing Story (Histoire de Modèles)",
    "date": "1974-1984",
    "cotes": [
      "134-1",
      "134-2",
      "134-3",
      "134-4",
      "134-5",
      "134-6",
      "134-7",
      "134-8",
      "135"
    ]
  },
  {
    "id": "136-137",
    "title": "Complexe de De Rham",
    "date": "[vers 1975-1976]",
    "cotes": [
      "136",
      "137",
      "138",
      "139"
    ]
  },
  {
    "id": "140-1-4",
    "title": "La \"Longue Marche\" à travers la théorie de Galois",
    "date": "[à partir de 1978-à partir de 1982]",
    "cotes": [
      "140-1",
      "140-2",
      "140-3",
      "140-4"
    ]
  },
  {
    "id": "141-149",
    "title": "Autour de La \"Longue Marche\" à travers la théorie de Galois",
    "date": "[à partir de 1978]-1983",
    "cotes": [
      "141",
      "142",
      "143",
      "144",
      "145",
      "146",
      "147",
      "148",
      "149"
    ]
  },
  {
    "id": "150-151",
    "title": "Espaces stratifiés",
    "date": "1981-[à partir de 1990]",
    "cotes": [
      "150",
      "151",
      "152",
      "153",
      "154",
      "155"
    ]
  },
  {
    "id": "156-1-9",
    "title": "Vers une géométrie des formes",
    "date": "1986",
    "cotes": [
      "156-1",
      "156-2",
      "156-3",
      "156-4",
      "156-5",
      "156-6",
      "156-7",
      "156-8",
      "156-9"
    ]
  },
  {
    "id": "157-1-5",
    "title": "Dérivateurs",
    "date": "1990-[1991]",
    "cotes": [
      "157-1",
      "157-2",
      "157-3",
      "157-4",
      "157-5",
      "158",
      "159",
      "160"
    ]
  },
  {
    "id": "161-1-6",
    "title": "Dossiers rassemblés par Grothendieck sur différentes thématiques",
    "date": "[après 1961-vers 1977]",
    "cotes": [
      "161-1",
      "161-2",
      "161-3",
      "161-4",
      "161-5",
      "161-6",
      "162-1",
      "162-5",
      "162-6"
    ]
  }
];

export const COTES: Cote[] = [
  {
    "id": "1",
    "file": "1.pdf",
    "date": "1953",
    "title": "Analyse fonctionnelle : notes manuscrites (s.d.), lettre (1953).",
    "pages": 149,
    "depth": 0,
    "group": "1-162"
  },
  {
    "id": "2",
    "file": "2.pdf",
    "date": "[1957]",
    "title": "Théorème de Riemann-Roch / RR [Riemann-Roch] Notes Antiques (antérieur[es à] 1958) : notes manuscrites (s.d.).",
    "pages": 44,
    "depth": 0,
    "group": "1-162"
  },
  {
    "id": "4",
    "file": "4.pdf",
    "date": "[à partir de 1958]",
    "title": "Torsion en cohomologie cristalline : notes manuscrites (s.d.), copies de tapuscrit annoté (s.d.).",
    "pages": 11,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "5",
    "file": "5.pdf",
    "date": "1965-1969",
    "title": "Cristaux et cohomologie de De Rham : généralités, correspondances Deligne et Berthelot (1965-1969) : notes manuscrites (s.d.), lettre (1965).",
    "pages": 52,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "6",
    "file": "6.pdf",
    "date": "1966-[à partir de 1970]",
    "title": "Lettre Tate (mai 66) (Cristaux) : lettre (1966), tapuscrit (s.d.), notes manuscrites (s.d.).",
    "pages": 66,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "7",
    "file": "7.pdf",
    "date": "1966-1967",
    "title": "Notes laïus novembre-décembre 1967 (Cristaux) : notes manuscrites (1966-1967).",
    "pages": 71,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "8",
    "file": "8.pdf",
    "date": "[vers 1967- vers 1971]",
    "title": "Cristaux (1970). Gribouillis et calculs divers : notes manuscrites (s.d.).",
    "pages": 80,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "9",
    "file": "9.pdf",
    "date": "[vers 1969]",
    "title": "Groupe de Barsotti-Tate et cristaux (jusqu’en été 1969) : notes manuscrites (s.d.).",
    "pages": 28,
    "depth": 1,
    "group": "4-9"
  },
  {
    "id": "10",
    "file": "10.pdf",
    "date": "[à partir de 1958]",
    "title": "Catégories tensorielles : notes manuscrites (s.d.), tapuscrits (s.d.).",
    "pages": 197,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "11",
    "file": "11.pdf",
    "date": "[à partir de 1961]",
    "title": "Formalisme des correspondances : notes manuscrites (s.d.).",
    "pages": 57,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "12",
    "file": "12.pdf",
    "date": "1964-[vers 1971]",
    "title": "Généralités (sous-groupes de Galois motiviques) (1964 ?) : notes manuscrites (s.d.), tapuscrit (s.d.).",
    "pages": 167,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "13",
    "file": "13.pdf",
    "date": "1965",
    "title": "Groupe de Galois motivique : notes manuscrites (s.d.), lettre (1965).",
    "pages": 51,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "14",
    "file": "14.pdf",
    "date": "1965-[vers 1971]",
    "title": "Théorie des cycles algébriques : conjectures de Hodge, Tate, Lefschetz, Weil : notes manuscrites (s.d.), lettre (1965).",
    "pages": 131,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "15",
    "file": "15.pdf",
    "date": "1965-[vers 1977]",
    "title": "Théorie arithmétique. Théorie de Galois des motifs (1965) : notes manuscites (s.d.), tapuscrit (s.d.).",
    "pages": 227,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "16",
    "file": "16.pdf",
    "date": "1966-1967",
    "title": "Formalisme algébrique des correspondances et algèbres de Poincaré-Hodge (cf conjectures standard) : notes manuscrites (s.d.), tapuscrit annoté (s.d.), lettres (1966-1967).",
    "pages": 55,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "18",
    "file": "18.pdf",
    "date": "[à partir de 1969-vers 1972]",
    "title": "Motifs et théorie de Hodge : notes manuscrites (s.d.).",
    "pages": 61,
    "depth": 1,
    "group": "10-18"
  },
  {
    "id": "19",
    "file": "19.pdf",
    "date": "[à partir de 1958-1973]",
    "title": "Topos : notes manuscrites (s.d.).",
    "pages": 95,
    "depth": 0,
    "group": "10-18"
  },
  {
    "id": "21",
    "file": "21.pdf",
    "date": "[vers 1960-1967]",
    "title": "[Chapitre] 0 III : tapuscrit et copies de tapuscrit annotés (s.d.), notes manuscrites (s.d.).",
    "pages": 28,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "22",
    "file": "22.pdf",
    "date": "1963-[vers 1967]",
    "title": "[EGA IV]. [Chapitre] 0 IV. Cohen, différentielles, algèbres formellement simples (Compléments) : tirés à part (1963), tapuscrit annoté (s.d.), notes manuscrites (s.d.).",
    "pages": 29,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "23",
    "file": "23.pdf",
    "date": "1966-1968",
    "title": "EGA IV. Compléments : notes manuscrites (s.d.), lettres (1966, 1968), tapuscrit (s.d.).",
    "pages": 98,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "24",
    "file": "24.pdf",
    "date": "[à partir de 1967-1987]",
    "title": "[EGA V, traduction en anglais] : copies de tapuscrit annoté (s.d.), notes manuscrites (s.d.).",
    "pages": 76,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "25",
    "file": "25.pdf",
    "date": "[à partir de 1967-1987]",
    "title": "Nouveau EGA V : copies de tapuscrits annotés (s.d.).",
    "pages": 184,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "26",
    "file": "26.pdf",
    "date": "[après 1967]",
    "title": "EGA VI. Plans, notations, problèmes ouverts : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 1,
    "group": "21-26"
  },
  {
    "id": "27",
    "file": "27.pdf",
    "date": "[vers 1962-1970]",
    "title": "SGA D [SGA 3]. Compléments XII à XVII : tapuscrit annoté (s.d.), notes manuscrites (s.d.).",
    "pages": 36,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "28",
    "file": "28.pdf",
    "date": "[vers 1970]",
    "title": "[Groupes algébriques (SGA 3)] : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "29",
    "file": "29.pdf",
    "date": "1959-1969",
    "title": "Groupe fondamental [Autour de SGA 4 et SGA 7] : lettres (1959, 1967, 1969), tapuscrits et copies de tapuscrit annotés (s.d.), notes manuscrites (s.d.).",
    "pages": 216,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "31",
    "file": "31.pdf",
    "date": "[1963-1973]",
    "title": "SGA A [SGA 4] (Résidus de rédaction) : notes manuscrites (s.d.).",
    "pages": 101,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "32",
    "file": "32.pdf",
    "date": "[vers 1963-1977]",
    "title": "Corrections (références, rajouts) [dont SGA 4] : tapuscrit (s.d.), notes manuscrites (s.d.).",
    "pages": 47,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "33",
    "file": "33.pdf",
    "date": "1965-[vers 1971]",
    "title": "SGA 1965. MS [Manuscrit] brouillon : notes manuscrites (s.d.).",
    "pages": 180,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "34",
    "file": "34.pdf",
    "date": "[vers 1967-1973]",
    "title": "SGA 7 : notes manuscrites (s.d.).",
    "pages": 209,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "35",
    "file": "35.pdf",
    "date": "[vers 1967-1973]",
    "title": "Plan [SGA 7] : notes manuscrites (s.d.), tapuscrit annoté (s.d.).",
    "pages": 5,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "36",
    "file": "36.pdf",
    "date": "[vers 1967-1973]",
    "title": "SGA 7 (ma part) : notes manuscrites (s.d.), tapuscrit annoté (s.d.).",
    "pages": 84,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "37",
    "file": "37.pdf",
    "date": "1967-1971",
    "title": "Rééditions SGA, EGA [SGA 4 à SGA 7, EGA I et EGA II] : tapuscrits et copies de tapuscrit annoté (s.d.), lettres (1967-1971, s.d.), notes manuscrites (s.d.).",
    "pages": 99,
    "depth": 1,
    "group": "27-38"
  },
  {
    "id": "39",
    "file": "39.pdf",
    "date": "[vers 1960-1970]",
    "title": "Fonctions et structures \" élémentaires\" [Schémas formels, théorème de préparation] : notes manuscrites (s.d.).",
    "pages": 19,
    "depth": 0,
    "group": "27-38"
  },
  {
    "id": "40",
    "file": "40.pdf",
    "date": "[années 1960-1970]",
    "title": "Calculs [affines sur des] fibrés principaux affines : notes manuscrites (s.d.).",
    "pages": 27,
    "depth": 0,
    "group": "27-38"
  },
  {
    "id": "41",
    "file": "41.pdf",
    "date": "[années 1960-1970]",
    "title": "Construction de morphismes étales (Chap. V) : notes manuscrites (s.d.).",
    "pages": 13,
    "depth": 0,
    "group": "27-38"
  },
  {
    "id": "42",
    "file": "42.pdf",
    "date": "[années 1960-1970]",
    "title": "Réseaux d'anneaux locaux : notes manuscrites (s.d.).",
    "pages": 6,
    "depth": 0,
    "group": "27-38"
  },
  {
    "id": "43",
    "file": "43.pdf",
    "date": "[à partir de 1961-vers 1968]",
    "title": "Dualité des groupes. Jacobiennes généralisées etc : notes et copies de notes manuscrites (s.d.).",
    "pages": 207,
    "depth": 1,
    "group": "43-44"
  },
  {
    "id": "44",
    "file": "44.pdf",
    "date": "1964",
    "title": "Jacobiennes intermédiaires : notes manuscrites (s.d.), lettre (1964).",
    "pages": 8,
    "depth": 1,
    "group": "43-44"
  },
  {
    "id": "45",
    "file": "45.pdf",
    "date": "1961-[vers 1970]",
    "title": "Groupes semi-simples : notes manuscrites (s.d.), tapuscrit annoté (1961).",
    "pages": 79,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "46",
    "file": "46.pdf",
    "date": "[vers 1966-vers 1972]",
    "title": "Schémas en groupes et fibrés principau[x] (Divers) : notes manuscrites (s.d.), tapuscrit (s.d.).",
    "pages": 94,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "47",
    "file": "47.pdf",
    "date": "s.d.",
    "title": "Produit de convolution sur les VA [variétés abéliennes] et transformation de Fourier dans les VA [variétés abéliennes] : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "48",
    "file": "48.pdf",
    "date": "[à partir de 1967]",
    "title": "Plan EGA VII : notes manuscrites (s.d.).",
    "pages": 5,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "49",
    "file": "49.pdf",
    "date": "s.d.",
    "title": "Picard des schémas abéliens : notes manuscrites (s.d.).",
    "pages": 9,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "50",
    "file": "50.pdf",
    "date": "[à partir de 1965]",
    "title": "Sur bouquin Lang : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "51",
    "file": "51.pdf",
    "date": "s.d.",
    "title": "\" Bonne réduction \" (Shimura-Koizumi) : notes manuscrites (s.d.).",
    "pages": 22,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "52",
    "file": "52.pdf",
    "date": "s.d.",
    "title": "Théorème de Torelli : notes manuscrites (s.d.).",
    "pages": 13,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "53",
    "file": "53.pdf",
    "date": "1973",
    "title": "Groupes algébriques : notes manuscrites (s.d.), lettre (1973).",
    "pages": 33,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "54",
    "file": "54.pdf",
    "date": "[à partir de 1971]",
    "title": "Dualité en cohomologie des V. A [variétés abéliennes] : notes manuscrites (s.d.).",
    "pages": 7,
    "depth": 1,
    "group": "45-54"
  },
  {
    "id": "55",
    "file": "55.pdf",
    "date": "[à partir de 1961]",
    "title": "Espaces analytiques : notes manuscrites (s.d.).",
    "pages": 17,
    "depth": 0,
    "group": "45-54"
  },
  {
    "id": "56",
    "file": "56.pdf",
    "date": "1962",
    "title": "Lefschetz-Hodge - Vanishing cycles : notes manuscrites (s.d.), tiré à part (1962).",
    "pages": 38,
    "depth": 0,
    "group": "45-54"
  },
  {
    "id": "57",
    "file": "57.pdf",
    "date": "1962-[vers 1968]",
    "title": "Picard : tapuscrit annoté (s.d.), lettres (s.d., 1962).",
    "pages": 314,
    "depth": 1,
    "group": "57-59"
  },
  {
    "id": "58",
    "file": "58.pdf",
    "date": "[à partir de 1964]",
    "title": "Théorie de \" Lefschetz-Grauert \". Applications en π₁, à Pic etc… : notes manuscrites (s.d.).",
    "pages": 66,
    "depth": 1,
    "group": "57-59"
  },
  {
    "id": "59",
    "file": "59.pdf",
    "date": "[années 1960-1970]",
    "title": "Construction des faisceaux inversibles sur schémas de Picard : notes manuscrites (s.d.).",
    "pages": 27,
    "depth": 1,
    "group": "57-59"
  },
  {
    "id": "60",
    "file": "60.pdf",
    "date": "[à partir de 1962- à partir de 1971]",
    "title": "Fonctions L / Équation fonctionnelle des fonctions L (cas géométrique) : notes manuscrites (s.d.).",
    "pages": 69,
    "depth": 0,
    "group": "57-59"
  },
  {
    "id": "62",
    "file": "62.pdf",
    "date": "[à partir de 1963]",
    "title": "Courbes elliptiques (généralités - vieille rédaction) : notes manuscrites (s.d.).",
    "pages": 96,
    "depth": 1,
    "group": "62-64"
  },
  {
    "id": "63",
    "file": "63.pdf",
    "date": "[à partir de 1964-vers 1970]",
    "title": "Formulaire courbes elliptiques : notes et copies de notes manuscrites (s.d.), tapuscrit (s.d.), copies d'articles (s.d.).",
    "pages": 100,
    "depth": 1,
    "group": "62-64"
  },
  {
    "id": "64",
    "file": "64.pdf",
    "date": "[à partir de 1980- 1982]",
    "title": "Modules courbes elliptiques en caractéristiques ≠2 : notes manuscrites (s.d.).",
    "pages": 156,
    "depth": 1,
    "group": "62-64"
  },
  {
    "id": "66",
    "file": "66.pdf",
    "date": "1964",
    "title": "Problèmes : notes manuscrites (1964).",
    "pages": 4,
    "depth": 1,
    "group": "66-89"
  },
  {
    "id": "67",
    "file": "67.pdf",
    "date": "[à partir de 1977]-1984",
    "title": "Chirurgie des surfaces conformes : notes manuscrites (s.d., 1983-1984), lettres (1984).",
    "pages": 100,
    "depth": 1,
    "group": "66-89"
  },
  {
    "id": "68",
    "file": "68.pdf",
    "date": "[à partir de 1978-à partir de 1983]",
    "title": "Jeux de position : notes manuscrites (s.d.).",
    "pages": 55,
    "depth": 1,
    "group": "66-89"
  },
  {
    "id": "69",
    "file": "69.pdf",
    "date": "[à partir de 1976]",
    "title": "Graphes cubiques : notes manuscrites (s.d.), lettre (s.d.).",
    "pages": 119,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "70",
    "file": "70.pdf",
    "date": "[à partir de 1976]",
    "title": "Réalisations géométriques de structures combinatoires (n-polyèdres, n-hyperpolyèdres [2-polyèdres réguliers]…) (Vieilles rédactions) : notes manuscrites (s.d.).",
    "pages": 125,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "71",
    "file": "71.pdf",
    "date": "[à partir de 1976]",
    "title": "Théorème de Jordan : notes manuscrites (1976, s.d.).",
    "pages": 47,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "72",
    "file": "72.pdf",
    "date": "[à partir de 1978]",
    "title": "Polyèdres réguliers et hyperpolyèdres réguliers (Calculs en dimension quelconque) : notes manuscrites (s.d.).",
    "pages": 112,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "73",
    "file": "73.pdf",
    "date": "[à partir de 1976]",
    "title": "Polygones : notes manuscrites (s.d.), lettre (s.d.).",
    "pages": 28,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "74",
    "file": "74.pdf",
    "date": "[à partir de 1976]",
    "title": "Complexes cubiques : notes manuscrites (s.d.).",
    "pages": 135,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "75",
    "file": "75.pdf",
    "date": "1977-1978",
    "title": "Cours C4, DEA : notes manuscrites (s.d.), lettre (1978), tapuscrit (1977-1978).",
    "pages": 32,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "76",
    "file": "76.pdf",
    "date": "[vers 1977]",
    "title": "n-cartes cellulaires : notes manuscrites (s.d.).",
    "pages": 62,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "77",
    "file": "77.pdf",
    "date": "[à partir de 1977]",
    "title": "Quadriques affines, extensions quadratiques : notes manuscrites (s.d.).",
    "pages": 157,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "78",
    "file": "78.pdf",
    "date": "[à partir de 1977]",
    "title": "[Polygones réguliers et polynômes cyclotomiques] : notes manuscrites (s.d.).",
    "pages": 129,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "79",
    "file": "79.pdf",
    "date": "[à partir de 1980]",
    "title": "2-polyèdres réguliers triangulés, et modules libres de rangs 2 sur les anneaux $\\Lambda=\\mathbb{Z}/n\\mathbb{Z}$ et $\\Lambda=\\mathbb{Z}$ : notes manuscrites (s.d.).",
    "pages": 296,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "80",
    "file": "80.pdf",
    "date": "[à partir de 1981]",
    "title": "Systèmes de pseudo-droites : notes manuscrites (s.d.).",
    "pages": 72,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "81",
    "file": "81.pdf",
    "date": "[à partir de 1981]",
    "title": "Immersions du disque et de la circonférence : notes manuscrites (s.d.).",
    "pages": 54,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "82",
    "file": "82.pdf",
    "date": "[vers 1982]",
    "title": "SO(3) ≃ GP(1) : notes manuscrites (s.d.).",
    "pages": 78,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "83",
    "file": "83.pdf",
    "date": "1982-1986",
    "title": "[Icosaèdres, bi-icosaèdres et algèbres d'Azumaya de rang 4] : notes manuscrites (1982-1983, 1986, s.d.).",
    "pages": 221,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "84",
    "file": "84.pdf",
    "date": "[à partir de 1982-vers 1986]",
    "title": "[Formes quadratiques] : notes manuscrites (s.d.).",
    "pages": 192,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "85",
    "file": "85.pdf",
    "date": "s.d.",
    "title": "2-polyèdres et 1-polygônes : notes manuscrites (s.d.).",
    "pages": 97,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "86",
    "file": "86.pdf",
    "date": "[à partir de 1977]",
    "title": "[Polyèdres réguliers] : notes manuscrites (s.d.).",
    "pages": 32,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "87",
    "file": "87.pdf",
    "date": "s.d.",
    "title": "Polyèdres convexes : notes manuscrites (s.d.).",
    "pages": 40,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "88",
    "file": "88.pdf",
    "date": "s.d.",
    "title": "Cartes standards : notes manuscrites (s.d.).",
    "pages": 15,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "89",
    "file": "89.pdf",
    "date": "s.d.",
    "title": "[Hexagone] combinatoire. [Ensembles 3-3] : notes manuscrites (s.d.).",
    "pages": 20,
    "depth": 2,
    "group": "69-89"
  },
  {
    "id": "90",
    "file": "90.pdf",
    "date": "[à partir de 1964]",
    "title": "KG (X) : notes manuscrites (s.d.).",
    "pages": 24,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "91",
    "file": "91.pdf",
    "date": "[à partir de 1964-vers 1970]",
    "title": "Autour de Néron / Greenberg-Néron. Foncteurs Hom (méthodes non-projectives) : notes manuscrites (s.d.), lettre (1967).",
    "pages": 142,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "93",
    "file": "93.pdf",
    "date": "[1972]-1981",
    "title": "Connexions de Gauss-Manin et équations de Picard-Fuchs. Opération de Cartier : copies de tapuscrit annoté (s.d.), tiré à part (1981), notes manuscrites (s.d.).",
    "pages": 235,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "94",
    "file": "94.pdf",
    "date": "[à partir de 1965]",
    "title": "Dualité des modules / Construction de faisceaux de modules : notes manuscrites (s.d.).",
    "pages": 23,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "97",
    "file": "97.pdf",
    "date": "[vers 1966]",
    "title": "Classes de Chern des représentations : lettre (1966), notes manuscrites (s.d.).",
    "pages": 18,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "98",
    "file": "98.pdf",
    "date": "[à partir de 1966-1967]",
    "title": "Schémas de Hilbert. Normes : notes manuscrites (s.d.).",
    "pages": 43,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "100",
    "file": "100.pdf",
    "date": "[à partir de 1967-1968]",
    "title": "Bonne réduction des variétés abéliennes via bonne réduction de Barsotti-Tate Tp (A) (base quelconque) : notes manuscrites (s.d.), copies de tapuscrit annoté (s.d.).",
    "pages": 52,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "101",
    "file": "101.pdf",
    "date": "[à partir de 1967-1968]",
    "title": "Cohomologie locale : notes manuscrites (s.d.).",
    "pages": 42,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "102",
    "file": "102.pdf",
    "date": "[après 1967]",
    "title": "Etude générale des foncteurs (Sch)° → (Ens) : tapuscrit annoté (s.d.), notes manuscrites (s.d.).",
    "pages": 13,
    "depth": 0,
    "group": "69-89"
  },
  {
    "id": "103",
    "file": "103.pdf",
    "date": "1974",
    "title": "Courrier [Correspondance sur la thèse de Sinh] : copies d'article annoté (1974), lettres (1974).",
    "pages": 17,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "104",
    "file": "104.pdf",
    "date": "s.d.",
    "title": "[Champs (stacks) 1] : copies de notes manuscrites (s.d.).",
    "pages": 16,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "105",
    "file": "105.pdf",
    "date": "[à partir de 1982]",
    "title": "[Champs (stacks) 2] : notes manuscrites (s.d.).",
    "pages": 52,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "106",
    "file": "106.pdf",
    "date": "[à partir de 1982]",
    "title": "[Champs (stacks) 3] : notes manuscrites (s.d.).",
    "pages": 16,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "107",
    "file": "107.pdf",
    "date": "[à partir de 1982]",
    "title": "Closed models [notes postérieures à PS ?] : notes manuscrites (s.d.).",
    "pages": 25,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "108",
    "file": "108.pdf",
    "date": "[à partir de 1973]",
    "title": "Divers, liste questions : notes manuscrites (s.d.).",
    "pages": 5,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "109",
    "file": "109.pdf",
    "date": "1983-1984",
    "title": "Tables [Corrections et préparation à l'édition] : notes manuscrites (s.d.), copies de notes manuscrites annotées (s.d.), copies de tapuscrit annoté (s.d.), copies de notes manuscrites (1983-1984).",
    "pages": 37,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "111",
    "file": "111.pdf",
    "date": "1968",
    "title": "Tapis de Quillen [notes du 10/09/1968] : copies de tapuscrit annoté (1968).",
    "pages": 16,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "112",
    "file": "112.pdf",
    "date": "s.d.",
    "title": "Linéarisation : notes manuscrites (s.d.).",
    "pages": 4,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "113",
    "file": "113.pdf",
    "date": "[à partir de 1982]",
    "title": "Abelianization : notes manuscrites (s.d.).",
    "pages": 12,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "114",
    "file": "114.pdf",
    "date": "[1983]",
    "title": "Asphéricité : notes manuscrites (s.d.).",
    "pages": 5,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "115",
    "file": "115.pdf",
    "date": "[à partir de 1982]",
    "title": "\" Correspondances \" fonctorielles. Dualité des topos : notes manuscrites (s.d.).",
    "pages": 14,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "116",
    "file": "116.pdf",
    "date": "[à partir de 1981]",
    "title": "Mapping-cône etc. : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "117",
    "file": "117.pdf",
    "date": "1983",
    "title": "Théories homotopiques : notes manuscrites (1983, s.d.).",
    "pages": 25,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "118",
    "file": "118.pdf",
    "date": "[à partir de 1983]",
    "title": "Cohomology properties of maps in (Cat) : notes manuscrites (s.d.).",
    "pages": 40,
    "depth": 1,
    "group": "103-118"
  },
  {
    "id": "119",
    "file": "119.pdf",
    "date": "1968-1991",
    "title": "Esquisse d’un programme [dossier constitué en vue d'une candidature au CNRS (1984)] : copies de tapuscrits et de tapuscrits annotés (1972-1974, 1978-1979, 1984, 1990-1991, s.d.), tirés à part (1971), notes et copies de note manuscrites (1986, s.d.), lettres (1968, 1972, 1991).",
    "pages": 313,
    "depth": 1,
    "group": "119-121"
  },
  {
    "id": "120",
    "file": "120.pdf",
    "date": "[à partir de 1973-à partir de 1978]",
    "title": "Topologie modérée : notes manuscrites (s.d.).",
    "pages": 24,
    "depth": 1,
    "group": "119-121"
  },
  {
    "id": "121",
    "file": "121.pdf",
    "date": "1974",
    "title": "Topologie modérée : notes manuscrites (s.d.), lettre (1974).",
    "pages": 72,
    "depth": 1,
    "group": "119-121"
  },
  {
    "id": "122",
    "file": "122.pdf",
    "date": "[vers 1968-1971]",
    "title": "Point singulier isolé de la fibre : notes manuscrites (s.d.).",
    "pages": 34,
    "depth": 0,
    "group": "119-121"
  },
  {
    "id": "123",
    "file": "123.pdf",
    "date": "1969",
    "title": "[Autour de Kostant] : tapuscrits (s.d.), notes manuscrites (s.d.), lettre (1969).",
    "pages": 47,
    "depth": 0,
    "group": "119-121"
  },
  {
    "id": "125",
    "file": "125.pdf",
    "date": "[avant 1970]",
    "title": "Dualité projective : notes manuscrites (s.d.).",
    "pages": 8,
    "depth": 0,
    "group": "119-121"
  },
  {
    "id": "126",
    "file": "126.pdf",
    "date": "s.d.",
    "title": "Descente fidèlement plate. Divers : notes manuscrites (s.d.).",
    "pages": 34,
    "depth": 1,
    "group": "126-128"
  },
  {
    "id": "127",
    "file": "127.pdf",
    "date": "s.d.",
    "title": "Descente non plate : notes manuscrites (s.d.).",
    "pages": 23,
    "depth": 1,
    "group": "126-128"
  },
  {
    "id": "128",
    "file": "128.pdf",
    "date": "s.d.",
    "title": "Descente non plate. Modules formels. Cf Notes Murre-Levelt : notes manuscrites (s.d.).",
    "pages": 31,
    "depth": 1,
    "group": "126-128"
  },
  {
    "id": "129",
    "file": "129.pdf",
    "date": "[1970]",
    "title": "Notes séminaire Montréal (Delale, Labute, Hakim, Messing) : copies de tapuscrits annotés (s.d.), notes manuscrites (s.d.).",
    "pages": 114,
    "depth": 0,
    "group": "126-128"
  },
  {
    "id": "130",
    "file": "130.pdf",
    "date": "[vers 1971]",
    "title": "Hauteurs et symboles locaux : notes manuscrites (s.d.).",
    "pages": 49,
    "depth": 0,
    "group": "126-128"
  },
  {
    "id": "131",
    "file": "131.pdf",
    "date": "[vers 1971]",
    "title": "Foncteurs représentables par schéma quasi fini : notes manuscrites (s.d.).",
    "pages": 41,
    "depth": 0,
    "group": "126-128"
  },
  {
    "id": "132",
    "file": "132.pdf",
    "date": "1974",
    "title": "Plongements dans surfaces (Ladegaillerie) : notes manuscrites (s.d.), tirés à part (1974).",
    "pages": 31,
    "depth": 0,
    "group": "126-128"
  },
  {
    "id": "133",
    "file": "133.pdf",
    "date": "1974-[à partir de 1975]",
    "title": "[Groupes de Witt et formes quadratiques, groupes formels] : notes manuscrites (s.d.), tirés à part (1974).",
    "pages": 53,
    "depth": 0,
    "group": "126-128"
  },
  {
    "id": "134-1",
    "file": "134-1.pdf",
    "date": "1974-1984",
    "title": "Lettres Breen 75,76 [correspondance avec Larry Breen, Pierre Deligne et Daniel Quillen] : lettres et copies de lettre (1974-1976, 1984).",
    "pages": 6,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-2",
    "file": "134-2.pdf",
    "date": "1975-[1983]",
    "title": "[Chapitre I : Take off (pages 1 à 65) et table des matières provisoire] : tapuscrits annotés (19/02-22/02/1983), note manuscrite (s.d.), copies de lettre (1975, s.d.).",
    "pages": 184,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-3",
    "file": "134-3.pdf",
    "date": "1983",
    "title": "[Chapitre II (points 14 à 44, pages 1 à 88) : Reflections on homotopical algebra et Notes for Chapter II] : tapuscrit annoté (27/02-26/03/1983).",
    "pages": 93,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-4",
    "file": "134-4.pdf",
    "date": "[1983]",
    "title": "[Chapitre III (pages 89 à 187) : Homotopy structures] : tapuscrit annoté (27/03-09/04/[1983]).",
    "pages": 100,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-5",
    "file": "134-5.pdf",
    "date": "[1983]",
    "title": "[Chapitre IV (pages 188 à 319) : Asphericity structures] : tapuscrit annoté (11/04-03/07/[1983]).",
    "pages": 132,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-6",
    "file": "134-6.pdf",
    "date": "[1983]",
    "title": "[Chapitre V (pages 320 à 442) : Homology and cohomology (abelianization of homotopy types)] : tapuscrit annoté (05/07-23/08/[1983]).",
    "pages": 124,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-7",
    "file": "134-7.pdf",
    "date": "[1983]",
    "title": "[Chapitre VI (pages 443 à 554) : Schematization] : tapuscrit annoté (24/08-16/09/[1983]).",
    "pages": 112,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "134-8",
    "file": "134-8.pdf",
    "date": "[1983]",
    "title": "[Chapitre VII (pages 555 à 593) : Linearization of homotopy types] : tapuscrit annoté (22/10-12/11/[1983]), notes manuscrites (s.d.).",
    "pages": 86,
    "depth": 1,
    "group": "134-1-8"
  },
  {
    "id": "135",
    "file": "135.pdf",
    "date": "[vers 1974]",
    "title": "Catégories [et Gr-catégories] : notes manuscrites (s.d.), copies de tapuscrit annoté (s.d.), copies de manuscrit annoté (s.d.).",
    "pages": 58,
    "depth": 0,
    "group": "134-1-8"
  },
  {
    "id": "136",
    "file": "136.pdf",
    "date": "[à partir de 1975-1976]",
    "title": "Complexe de De Rham à puissance divisée [conférence de 1976 à l’IHÉS] : notes manuscrites (s.d.).",
    "pages": 375,
    "depth": 1,
    "group": "136-137"
  },
  {
    "id": "137",
    "file": "137.pdf",
    "date": "[vers 1975-1976]",
    "title": "Dévissage des complexes ½ simpliciaux ∂ - parfaits et structures multiplicatives… (1975 ou 1976) : notes manuscrites (s.d.).",
    "pages": 85,
    "depth": 1,
    "group": "136-137"
  },
  {
    "id": "138",
    "file": "138.pdf",
    "date": "[vers 1976-1978]",
    "title": "Cartes. Etude arithmétique (1976, 77 ?) : bon de commande (s.d.), notes manuscrites (s.d.).",
    "pages": 132,
    "depth": 0,
    "group": "136-137"
  },
  {
    "id": "139",
    "file": "139.pdf",
    "date": "1977",
    "title": "[Prix Émile Picard de l'Académie des Sciences de l'Institut de France] : médaille.",
    "pages": 2,
    "depth": 0,
    "group": "136-137"
  },
  {
    "id": "140-1",
    "file": "140-1.pdf",
    "date": "[à partir de 1978-à partir de 1982]",
    "title": "\"Longue Marche\" [brouillon] : notes manuscrites (s.d.).",
    "pages": 36,
    "depth": 1,
    "group": "140-1-4"
  },
  {
    "id": "140-2",
    "file": "140-2.pdf",
    "date": "s.d.",
    "title": "La \"Longue Marche\" à travers la théorie de Galois… [pages 1 à 292, dont table des matières] : notes manuscrites (s.d.).",
    "pages": 574,
    "depth": 1,
    "group": "140-1-4"
  },
  {
    "id": "140-3",
    "file": "140-3.pdf",
    "date": "s.d.",
    "title": "Deuxième partie : variations sur l'équation des lacets [suite à La \"Longue Marche\" à travers la théorie de Galois…, pages 293 à 650, dont table des matières] : notes et copies de notes manuscrites (s.d.).",
    "pages": 695,
    "depth": 1,
    "group": "140-1-4"
  },
  {
    "id": "140-4",
    "file": "140-4.pdf",
    "date": "s.d.",
    "title": "[suite à La \"Longue Marche\" à travers la théorie de Galois..., pages 650 bis à 787, dont table des matières] : notes manuscrites (s.d.).",
    "pages": 279,
    "depth": 1,
    "group": "140-1-4"
  },
  {
    "id": "141",
    "file": "141.pdf",
    "date": "[à partir de 1980]",
    "title": "Théorie de Kumer ? + note Alexandre (bi tenseur…) : notes manuscrites (s.d.).",
    "pages": 15,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "142",
    "file": "142.pdf",
    "date": "[à partir de 1978]",
    "title": "Action de Galois sur Teichmüller : notes manuscrites (s.d.).",
    "pages": 121,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "143",
    "file": "143.pdf",
    "date": "[vers 1980-1981]",
    "title": "Paradigmes des courbes algébriques (version provisoire) : notes manuscrites (s.d.).",
    "pages": 33,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "144",
    "file": "144.pdf",
    "date": "1981-1983",
    "title": "[Suite autour de Teichmüller dont] Teichmülleries, 1981-1982 : notes manuscrites (1981-1983, s.d.), lettres (1981, s.d.).",
    "pages": 183,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "145",
    "file": "145.pdf",
    "date": "1981",
    "title": "Printemps 81 (vieille rédaction) : notes manuscrites (s.d.).",
    "pages": 37,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "146",
    "file": "146.pdf",
    "date": "[à partir de 1978]",
    "title": "Groupoïdes de Teichmüller et les S0 Tg,!ν, S0 TG : notes manuscrites (s.d.).",
    "pages": 133,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "147",
    "file": "147.pdf",
    "date": "s.d.",
    "title": "Structure à l'infini des Mg,ν [pages 1 à 90, dont table des matières] : notes manuscrites (s.d.).",
    "pages": 189,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "148",
    "file": "148.pdf",
    "date": "1983",
    "title": "Teichmüller (1983) : notes manuscrites (1983).",
    "pages": 71,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "149",
    "file": "149.pdf",
    "date": "s.d.",
    "title": "[Autour de La \"Longue Marche\" à travers la théorie de Galois, pages 1 à 67] : notes manuscrites (s.d.).",
    "pages": 135,
    "depth": 1,
    "group": "141-149"
  },
  {
    "id": "150",
    "file": "150.pdf",
    "date": "1981-1982",
    "title": "Espaces stratifiés et voisinages côniques (ou : déploiement des espaces stratifiés) : notes manuscrites (s.d.).",
    "pages": 98,
    "depth": 1,
    "group": "150-151"
  },
  {
    "id": "151",
    "file": "151.pdf",
    "date": "[à partir de 1981-à partir de 1990]",
    "title": "Topos stratifié (1981) : notes manuscrites (s.d.).",
    "pages": 74,
    "depth": 1,
    "group": "150-151"
  },
  {
    "id": "152",
    "file": "152.pdf",
    "date": "[à partir de 1982]",
    "title": "Catégorie des types de mots [dont arbres plans] : notes manuscrites (s.d.).",
    "pages": 12,
    "depth": 0,
    "group": "150-151"
  },
  {
    "id": "153",
    "file": "153.pdf",
    "date": "[à partir de 1982]",
    "title": "Analyseurs : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 0,
    "group": "150-151"
  },
  {
    "id": "154",
    "file": "154.pdf",
    "date": "1983-1984",
    "title": "[Système de pseudo-droites] : notes manuscrites (1983-1984, s.d.).",
    "pages": 175,
    "depth": 0,
    "group": "150-151"
  },
  {
    "id": "155",
    "file": "155.pdf",
    "date": "[à partir de 1984]",
    "title": "[Rigidité de catégories tensorielles ?] : notes manuscrites (s.d.).",
    "pages": 10,
    "depth": 0,
    "group": "150-151"
  },
  {
    "id": "156-1",
    "file": "156-1.pdf",
    "date": "1986",
    "title": "[Chapitre] I. Vers une géométrie des formes (topologiques) : notes manuscrites (05/06/1986).",
    "pages": 26,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-2",
    "file": "156-2.pdf",
    "date": "1986",
    "title": "[Chapitre] II. Réalisations topologiques des réseaux : notes manuscrites (06/06/1986).",
    "pages": 18,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-3",
    "file": "156-3.pdf",
    "date": "1986",
    "title": "[Chapitre] III. Réseaux via découpages : notes manuscrites (08/06/1986).",
    "pages": 40,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-4",
    "file": "156-4.pdf",
    "date": "1986",
    "title": "[Chapitre] IV. Analysis situs (première mouture) : notes manuscrites (10/06/1986).",
    "pages": 88,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-5",
    "file": "156-5.pdf",
    "date": "1986",
    "title": "[Chapitre] V. Algèbre des figures : notes manuscrites (14/06/1986).",
    "pages": 48,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-6",
    "file": "156-6.pdf",
    "date": "1986",
    "title": "[Chapitre] VI. Analysis situs (deuxième mouture) : notes manuscrites (18-20/06/1986).",
    "pages": 93,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-7",
    "file": "156-7.pdf",
    "date": "1986",
    "title": "[Chapitre] VII. Analysis situs (troisième mouture) : notes manuscrites (23-26/06/1986).",
    "pages": 113,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-8",
    "file": "156-8.pdf",
    "date": "1986",
    "title": "[Chapitre] VIII. Analysis situs (quatrième mouture) : notes manuscrites (26/06-04/07/1986).",
    "pages": 126,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "156-9",
    "file": "156-9.pdf",
    "date": "1986",
    "title": "[Chapitre] IX et IX bis. [Ateliers] : notes manuscrites (05-15/07/1986).",
    "pages": 139,
    "depth": 1,
    "group": "156-1-9"
  },
  {
    "id": "157-1",
    "file": "157-1.pdf",
    "date": "s.d.",
    "title": "Dérivateurs [chapitres I à IV, dont sommaire général] : notes manuscrites (s.d.).",
    "pages": 270,
    "depth": 1,
    "group": "157-1-5"
  },
  {
    "id": "157-2",
    "file": "157-2.pdf",
    "date": "1990",
    "title": "Dérivateurs [chapitres V à VIII] : notes manuscrites (1990, s.d.).",
    "pages": 441,
    "depth": 1,
    "group": "157-1-5"
  },
  {
    "id": "157-3",
    "file": "157-3.pdf",
    "date": "1990",
    "title": "Dérivateurs [chapitres IX à XII, dont sommaire et appendices du chapitre XII] : notes manuscrites (s.d., 1990).",
    "pages": 355,
    "depth": 1,
    "group": "157-1-5"
  },
  {
    "id": "157-4",
    "file": "157-4.pdf",
    "date": "s.d.",
    "title": "Dérivateurs [chapitres XIII à XVI, dont sommaire du chapitre XVI] : notes manuscrites (s.d.).",
    "pages": 408,
    "depth": 1,
    "group": "157-1-5"
  },
  {
    "id": "157-5",
    "file": "157-5.pdf",
    "date": "s.d.",
    "title": "Dérivateurs [chapitres XVII à XIX, dont sommaires de chacun des chapitres] : notes manuscrites (s.d.).",
    "pages": 661,
    "depth": 1,
    "group": "157-1-5"
  },
  {
    "id": "158",
    "file": "158.pdf",
    "date": "[vers 1990-1991]",
    "title": "[Autour des Dérivateurs] : notes manuscrites (s.d.).",
    "pages": 85,
    "depth": 0,
    "group": "157-1-5"
  },
  {
    "id": "159",
    "file": "159.pdf",
    "date": "s.d.",
    "title": "Connexions projectives et uniformisation : notes manuscrites (s.d.).",
    "pages": 33,
    "depth": 0,
    "group": "157-1-5"
  },
  {
    "id": "160",
    "file": "160.pdf",
    "date": "s.d.",
    "title": "Schémas [en] groupes : notes manuscrites (s.d.).",
    "pages": 22,
    "depth": 0,
    "group": "157-1-5"
  },
  {
    "id": "161-1",
    "file": "161-1.pdf",
    "date": "s.d.",
    "title": "Catégories : notes manuscrites (s.d.).",
    "pages": 19,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "161-2",
    "file": "161-2.pdf",
    "date": "[vers 1963-1973]",
    "title": "Algèbre universelle [ou catégories] : notes manuscrites (s.d.).",
    "pages": 111,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "161-3",
    "file": "161-3.pdf",
    "date": "[vers 1963-1973]",
    "title": "Topos : notes manuscrites (s.d.).",
    "pages": 54,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "161-4",
    "file": "161-4.pdf",
    "date": "[après 1961]",
    "title": "Introduction à géométrie algébrique : notes manuscrites (s.d.).",
    "pages": 31,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "161-5",
    "file": "161-5.pdf",
    "date": "1967-1969",
    "title": "Barsotti-Tate : tirés à part annotés (1967-1969), notes manuscrites (s.d.).",
    "pages": 28,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "161-6",
    "file": "161-6.pdf",
    "date": "[à partir de 1973-vers 1977]",
    "title": "Graphes, icosaèdre [etc.] : notes manuscrites (s.d.).",
    "pages": 33,
    "depth": 1,
    "group": "161-1-6"
  },
  {
    "id": "162-1",
    "file": "162-1.pdf",
    "date": "[à partir de 1967]",
    "title": "Papiers prêtés [liste de noms et de références documentaires] : notes manuscrites (s.d.).",
    "pages": 9,
    "depth": 0,
    "group": "161-1-6"
  },
  {
    "id": "162-5",
    "file": "162-5.pdf",
    "date": "1968-[à partir de 1970]",
    "title": "Tapis de Quillen : tapuscrit et copies de tapuscrits (1968, s.d.), notes manuscrites (1968), tiré à part (1968).",
    "pages": 68,
    "depth": 0,
    "group": "161-1-6"
  },
  {
    "id": "162-6",
    "file": "162-6.pdf",
    "date": "s.d.",
    "title": "[Documents isolés] : notes manuscrites (s.d.).",
    "pages": 5,
    "depth": 0,
    "group": "161-1-6"
  }
];

export const BY_ID = new Map(COTES.map((c) => [c.id, c]));
