import type { PlainItem } from '../lib/types.ts';

/**
 * What the edition has turned up, in plain words (#29, part 2).
 *
 * Twelve items drawn from `findings.ts`, chosen for being statable to a
 * non-specialist and worth someone's afternoon to check — not a ranking of
 * the mathematics. The register is the one the outreach letters had to be
 * written in: hypotheses, never results; no priority, since the folders are
 * undated; and the caveats on every item rather than in a preamble.
 *
 * `ours` is the reason this file exists. The Findings list records row by row
 * what the edition supplied; a summary that let those steps disappear inside
 * « Grothendieck's unpublished ideas » would be the most misleading page this
 * project could publish. Where `ours` is long, that is the item to distrust.
 */
export const PLAIN: PlainItem[] = [
  {
    id: 'lefschetz-without-module',
    cote: '16',
    rows: ['16-graded-ring-lefschetz-criterion'],
    title: 'A test for the Lefschetz package that needs no cohomology',
    what:
      'The hard Lefschetz theorem is usually stated for a cohomology group with an operator L acting on it. Folder 16 works one level up. Given only a graded ring and an element L of degree 2, it asks what must hold in the ring itself for the usual consequences — the pseudo-inverse Λ, the projectors of the primitive decomposition — to exist there. Its answer is a short list of one-sided inverses, and the argument works over the integers, not only over a field.',
    ours:
      'The page’s list of conditions is struck out and renumbered three times, and one implication is marked « Démonstration à fournir ». The three-clause statement is the edition’s reconstruction from what pages 10 to 12 actually prove.',
    settle:
      'Kleiman’s two surveys of the standard conjectures (1968 and 1994): is this criterion stated anywhere for an abstract ring, with no module, and over ℤ?',
  },
  {
    id: 'universal-lefschetz-ring',
    cote: '16',
    rows: ['16-universal-lefschetz-ring'],
    title: 'One ring that carries the whole Lefschetz package — and a slip on the page',
    what:
      'The same folder builds a single ring, generated by two operators L₀ and Λ₀, such that a graded ring satisfies the Lefschetz conditions exactly when this universal ring maps into it. The whole package becomes one algebraic object.',
    ours:
      'Here the edition disagrees with the page. The leaf gives the name Λ₀ to two different operators, which agree only in rank one. The reading keeps the one the proof actually uses and says so in a footnote. If that call is wrong, this item is wrong with it.',
    settle:
      'Compare with the « Lefschetz algebras » of Hodge theory, and with the integral form of the enveloping algebra of sl₂ — which, because of that slip, this ring is not.',
  },
  {
    id: 'any-algebraic-isomorphism',
    cote: '16',
    rows: ['16-algebraic-iso-suffices'],
    title: 'Any algebraic isomorphism will do',
    what:
      'One of Grothendieck’s standard conjectures asks that the Lefschetz isomorphism between cohomology in complementary degrees come from an algebraic cycle. Folder 16 argues that it is enough to have some algebraic isomorphism in each degree — any one, not necessarily the Lefschetz map — together with a second conjecture, D(X). The argument is complete on the page.',
    ours: 'Almost nothing: the typescript writes one relation in the letter u where its coefficients are those of w.',
    settle:
      'The argument is short enough that it is probably in the books already. Kleiman’s 1994 survey, § 2, is where it would be.',
  },
  {
    id: 'products-of-spaces',
    cote: '161-3',
    rows: ['161-3-product-converse', '161-3-infinite-product-criterion'],
    title: 'When the sheaves on a product are determined by the factors',
    what:
      'For topological spaces X and Y, the topos of sheaves on X × Y is not in general the product of the topoi of X and of Y. The textbook condition that makes it so is local compactness. Folder 161-3 proves it under a weaker condition — every non-empty locally closed piece of X has a point with a relatively quasi-compact neighbourhood inside it — and states a version for infinite products with two separate « all factors but one » clauses.',
    ours:
      'The proof on the page skips an inclusion without which its contradiction does not go through. The reading supplies it. That step is ours, not his, and it is the first place to look for a mistake.',
    settle:
      'Johnstone, Stone Spaces II.4 and the Elephant C1.1 and C4.1, and Isbell on products of locales: is this hypothesis, or the two-clause infinite form, already there?',
  },
  {
    id: 'spatiality-proof',
    cote: '161-3',
    rows: ['161-3-locale-spatiality-suprema-proof'],
    title: 'A different proof of a known theorem',
    what:
      'That such products behave well as locales is published. What the folder has is a proof of it: three passages to a supremum in the lattice of open sets, self-contained. The claim is only that this argument is not the one in the books — the theorem certainly is.',
    ours:
      'The reading states the non-emptiness the page assumes in passing, and names two topologies the page distinguishes without labelling them.',
    settle:
      'Read it side by side with the proof in Johnstone’s Stone Spaces and decide whether it is the same argument in other clothes.',
  },
  {
    id: 'hypercoverings-without-simplices',
    cote: '151',
    rows: ['151-hypercovering-any-index-category'],
    title: 'Hypercoverings without simplices',
    what:
      'A hypercovering is the device that computes the cohomology of a space from better and better approximations of it, and it is normally indexed by the simplicial category Δ. Folder 151 defines one for any small index category, by a single condition: a certain comparison map must be an epimorphism for every finite diagram.',
    ours: 'The reading names a construction the page writes without naming (a left Kan extension). Nothing else.',
    settle:
      'Is this condition a definition anywhere — SGA 4 V, Artin–Mazur, Dugger–Hollander–Isaksen (2004), or the covering-flat functors of Shulman and of Kondô–Yasuda?',
  },
  {
    id: 'stratified-from-neighbours',
    cote: '151',
    rows: ['151-tube-gluing-covering-pairs', '151-mixed-tubes'],
    title: 'Rebuilding a stratified space from neighbouring strata only',
    what:
      'A stratified space is cut into pieces of different dimensions, each lying along the boundary of the next. Folder 151 rebuilds the whole space from a diagram that looks only at neighbouring pairs of strata — three maps per pair, and no comparison between strata that are not adjacent. It also introduces « mixed tubes » that interpolate between a stratum’s neighbourhood with the stratum removed and its full neighbourhood.',
    ours:
      'A lot, and this is the item to distrust most. The word naming the gluing operation on page 68 is illegible; the reading takes it to be the colimit. The mixed tubes, as the page defines them, would all be the same, and two of the page’s own identities would be false; the reading changes one index so that they hold. The item is about the corrected definition, not the sentence on the page.',
    settle:
      'Quinn on homotopically stratified sets, Lurie’s Higher Algebra A.9, Ayala–Francis–Tanaka: is the reconstruction from adjacent pairs alone already the standard statement?',
  },
  {
    id: 'ramification-domains',
    cote: '29',
    rows: ['29-ramification-domain-axioms'],
    title: 'Axioms for ramified coverings',
    what:
      'Galois categories say abstractly what the unramified coverings of a scheme form. Folder 29 attempts the same for ramified ones: a « domaine de ramification » is a stack of categories over the étale site with a « geometric realisation » into schemes, subject to four axioms R1–R4. Given three of them, the fourth is shown to be equivalent to the realisation being faithful.',
    ours:
      'The page proves one direction of that equivalence; the reading states both. Axiom R4 has three illegible words, and the page the equivalence rests on is struck through by its author.',
    settle: 'First settle from the leaf what R4 says. Only then compare with modern axiomatisations of Galois categories without a fibre functor.',
  },
  {
    id: 'counting-sheets-without-points',
    cote: '29',
    rows: ['29-degree-n-as-primitive'],
    title: 'Counting sheets without points',
    what:
      'The degree of a covering is usually the number of points in a fibre. Folder 29 takes « degree n » as primitive instead: six conditions on a class of morphisms determine it uniquely, and it then agrees with the usual notion. The point is to say that a covering has n sheets in a setting with no points to count.',
    ours:
      'The reading says what the axioms are for; the page does not. Two items of the surrounding list are largely illegible, so only the degree axioms themselves are claimed.',
    settle: 'Compare with the fibre-functor-free axiomatisations of Galois categories, where the decomposition by degree already appears.',
  },
  {
    id: 'local-test-cohomological-dimension',
    cote: '31',
    rows: ['31-phi-specialisation-criterion'],
    title: 'A local test for cohomological dimension',
    what:
      'To bound the étale cohomological dimension of a noetherian scheme, folder 31 asks for any function φ on its points with two local properties: at each point φ is at least the dimension of the residue field, and it drops by enough along every specialisation. Cohomology then vanishes above the largest value of φ.',
    ours:
      'The names of the two conditions, and the reason for the amount subtracted, are the reading’s; the statements and the proof are the page’s. The prose around one condition on page 66 is largely illegible, and the item does not rest on it.',
    settle: 'SGA 4, Exposés X and XVIII: is the criterion stated there for an arbitrary φ, or only for the particular functions it is applied to?',
  },
  {
    id: 'topos-of-fields',
    cote: '161-2',
    rows: ['161-2-field-classifier-absolutely-flat-site'],
    title: 'The topos of fields, through absolutely flat rings',
    what:
      'There is a topos whose points are the fields — the classifying topos of fields. Folder 161-2 presents it through absolutely flat (von Neumann regular) rings with one covering condition, instead of through ordinary finitely presented rings. It is one of only three mathematical items on this page anyone has looked up, and the search was thin: one source cited from memory, one found by search.',
    ours:
      'Translating the page’s terms into absolutely flat rings, and reading its topology, is the edition’s work. Page 94 is a fast draft with illegible connectives.',
    settle:
      'Read which site Johnstone (1977) and Caramello (arXiv 0808.1519) use for fields. If it is this one or an easy variant of it, the item is in the literature.',
  },
  {
    id: 'involutions-of-modules',
    cote: '67',
    rows: ['67-involution-modules-triples'],
    title: 'Involutions of a module, classified',
    what:
      'An involution of a module is a map σ with σ² = 1. When 2 is invertible it splits the module into a +1 part and a −1 part, and nothing more is needed. Folder 67 treats the case where multiplication by 2 is only injective: the involution is then the two parts plus one small piece of data modulo 2 gluing them, and this is an equivalence of categories, with no finiteness assumption.',
    ours: 'The check that no finiteness assumption is needed is the edition’s.',
    settle:
      'Over ℤ this is classical (Reiner, 1957). The open question is the general statement; look first in the literature on modules over pullback rings (L. S. Levy).',
  },
];
