#!/usr/bin/env node
/**
 * Builds the local mirror of the fonds, cut into twenty-page batches.
 *
 *   npm run archive -- topos                 a whole notebook
 *   npm run archive -- 19 161-3 115          named folders
 *   npm run archive -- topos --batches 1-3   only the first three batches
 *
 * Why a mirror rather than a link to Montpellier — two reasons, neither a
 * choice:
 *
 * — **Montpellier refuses to be framed.** It serves
 *   `X-Frame-Options: SAMEORIGIN`, so no other origin may embed it, whatever
 *   else is true. Its certificate has also expired (10 December 2025), which
 *   fails TLS verification besides — and the interstitial that would let one
 *   proceed does not render inside a frame. The right-hand pane would stay
 *   blank on either count.
 * — **The originals run from 4 MB to 270 MB.** The Long March is 204 MB for
 *   one of its four volumes alone. Even served correctly that does not open in
 *   a side pane, and above all it does not reopen twenty times during a
 *   transcription.
 *
 * So the twenty-page batch is not merely a display convenience: it is the unit
 * of transcription, and it is the same object on both sides. What one reads in
 * the pane is exactly what one hands over to be transcribed — not an extract,
 * not a rendering, the file itself.
 *
 * Cutting is done with pdf-lib rather than with poppler's `pdfseparate`, and
 * that is not a preference. These PDFs are LaTeX wrappers around a pool of
 * scanned JPEGs, and poppler cannot prune that pool — it warns about
 * "recursive dicts" and gives up, so every single extracted page carries all
 * ninety-odd images of the folder with it. Measured on folder 19: a one-page
 * extract came to 35 MB, a twenty-page batch to 42 MB, larger than the whole
 * source. pdf-lib walks the object graph properly and gives 7.1 MB for the
 * same twenty pages.
 *
 * The price is memory: pdf-lib holds the document in RAM, so the heaviest
 * folders — 270 MB for Dérivateurs V — need the enlarged heap the npm script
 * asks for. Poppler is still used for `pdfinfo` and `pdftoppm`, which only
 * read.
 */

import { execFile } from 'node:child_process';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { promisify } from 'node:util';
import { resolve } from 'node:path';
import { PDFDocument } from 'pdf-lib';
import { writeManifest } from './manifest.mjs';

const exec = promisify(execFile);

/** See the catalogue script's note: expired certificate, intact identity. */
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const ROOT = resolve(import.meta.dirname, '..');
const RAW = resolve(ROOT, 'archives', 'raw');
const BATCHES = resolve(ROOT, 'archives', 'batches');
const THUMBS = resolve(ROOT, 'archives', 'thumbs');
const BASE = 'https://grothendieck.umontpellier.fr/';

/** Twenty pages: one transcription pass. */
const BATCH_SIZE = 20;

// ---------------------------------------------------------------------------

async function requireTools() {
  try {
    await exec('which', ['pdfinfo']);
  } catch {
    throw new Error('`pdfinfo` not found. Install poppler: brew install poppler');
  }
}

async function sizeOf(path) {
  try {
    return (await stat(path)).size;
  } catch {
    return 0;
  }
}

const mb = (b) => `${(b / 1e6).toFixed(1)} MB`;

/** The original PDF, downloaded once and kept. */
async function download(cote) {
  const target = resolve(RAW, `${cote}.pdf`);
  const url = `${BASE}${cote}.pdf`;

  const head = await fetch(url, { method: 'HEAD' });
  if (!head.ok) throw new Error(`${url} → HTTP ${head.status}`);
  const expected = Number(head.headers.get('content-length') ?? 0);

  const already = await sizeOf(target);
  if (already && already === expected) {
    process.stdout.write(`  folder ${cote}: already here (${mb(already)})\n`);
    return target;
  }

  process.stdout.write(`  folder ${cote}: downloading ${mb(expected)}…`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(target));
  process.stdout.write(' done\n');
  return target;
}

async function pageCount(pdf) {
  const { stdout } = await exec('pdfinfo', [pdf]);
  return Number(/^Pages:\s+(\d+)$/m.exec(stdout)?.[1] ?? 0);
}

/**
 * Cuts a folder into twenty-page batches.
 *
 * Page 1 of the PDF is a cover sheet generated by Montpellier — title,
 * shelfmark, dating — and not a page of Grothendieck's. It is therefore left
 * out of the cut, so that "page 1 of batch 1" really is the first digitised
 * page, and the site's numbering agrees with the inventory's ("Cote n° 26, 10
 * pages") rather than with the file's.
 *
 * Each batch is reassembled, never re-rendered: it is the original PDF, its
 * images at their original resolution, with the rest cut away. A transcription
 * made on a batch is a transcription made on the source.
 */
async function cut(cote, pdf, wanted) {
  const pdfPages = await pageCount(pdf);
  const pages = pdfPages - 1;
  if (pages < 1) throw new Error(`folder ${cote}: PDF with no page?`);

  const dir = resolve(BATCHES, cote);
  await mkdir(dir, { recursive: true });

  const count = Math.ceil(pages / BATCH_SIZE);
  const todo = [];
  for (let k = 1; k <= count; k++) {
    if (wanted && !wanted(k)) continue;
    const target = resolve(dir, `batch-${String(k).padStart(2, '0')}.pdf`);
    if (!(await sizeOf(target))) todo.push({ k, target });
  }

  if (todo.length) {
    // Parsed once for the whole folder. On Dérivateurs V that is a 270 MB
    // parse; doing it per batch would repeat it thirty-four times.
    const source = await PDFDocument.load(await readFile(pdf), { updateMetadata: false });

    for (const { k, target } of todo) {
      // Zero-based indices inside the PDF: the cover sheet is index 0, so page
      // 1 is index 1.
      const from = (k - 1) * BATCH_SIZE + 1;
      const to = Math.min(k * BATCH_SIZE, pages);

      const out = await PDFDocument.create();
      const pages = await out.copyPages(
        source,
        Array.from({ length: to - from + 1 }, (_, i) => from + i),
      );
      for (const p of pages) out.addPage(p);
      await writeFile(target, await out.save());

      process.stdout.write(
        `  folder ${cote}: batch ${k}/${count} — pages ${from}–${to} ` +
          `(${mb(await sizeOf(target))})\n`,
      );
    }
  }

  await thumbnail(cote, pdf);
}

/** A thumbnail of the first page, so a folder list shows the handwriting. */
async function thumbnail(cote, pdf) {
  const target = resolve(THUMBS, `${cote}.jpg`);
  if (await sizeOf(target)) return;
  await mkdir(THUMBS, { recursive: true });
  try {
    await exec('pdftoppm', [
      '-jpeg', '-r', '30', '-f', '2', '-l', '2', '-singlefile',
      pdf, target.replace(/\.jpg$/, ''),
    ]);
  } catch {
    // pdftoppm absent or page unreadable: the list renders without a thumbnail.
  }
}

// ---------------------------------------------------------------------------

/** `--batches 1-3` or `--batches 1,4,7`: enough to start without pulling everything. */
function parseWanted(args) {
  const i = args.indexOf('--batches');
  if (i < 0) return null;
  const spec = args[i + 1] ?? '';
  const set = new Set();
  for (const part of spec.split(',')) {
    const range = /^(\d+)-(\d+)$/.exec(part.trim());
    if (range) for (let k = Number(range[1]); k <= Number(range[2]); k++) set.add(k);
    else if (part.trim()) set.add(Number(part.trim()));
  }
  return (k) => set.has(k);
}

async function main() {
  const args = process.argv.slice(2);
  const wanted = parseWanted(args);
  const iBatches = args.indexOf('--batches');
  const asked = args.filter((a, i) => !a.startsWith('--') && !(iBatches >= 0 && i === iBatches + 1));

  if (!asked.length) {
    process.stderr.write(
      'Usage: npm run archive -- <notebook|folder…> [--batches 1-3]\n' +
        '  notebooks: topos, motives, long-march, late\n',
    );
    process.exit(1);
  }

  await requireTools();
  await mkdir(RAW, { recursive: true });

  // Notebooks are described in JSON rather than TypeScript so that the site and
  // this script read the same list of folders, and there are not two places to
  // get it wrong the day a notebook grows.
  const books = JSON.parse(await readFile(resolve(ROOT, 'src', 'content', 'books.json'), 'utf8'));

  const cotes = [];
  for (const a of asked) {
    const b = books.find((x) => x.key === a);
    if (b) cotes.push(...b.sections.flatMap((s) => s.cotes));
    else cotes.push(a);
  }

  for (const cote of new Set(cotes)) {
    process.stdout.write(`\n${cote}\n`);
    try {
      const pdf = await download(cote);
      await cut(cote, pdf, wanted);
    } catch (e) {
      process.stderr.write(`  ⚠ folder ${cote}: ${e.message}\n`);
    }
  }

  await writeManifest();
}

main().catch((e) => {
  process.stderr.write(`${e.message}\n`);
  process.exit(1);
});
