#!/usr/bin/env node
/**
 * Rebuilds `src/content/catalogue.ts` from Montpellier's inventory page.
 *
 * The inventory exists nowhere as data: it is encoded in the HTML of a
 * WordPress accordion. We read it rather than copy it, for two reasons — a
 * hand transcription of 178 shelfmarks gets things wrong, and the day
 * Montpellier corrects a dating or opens a folder, re-running this script is
 * enough for the site to follow.
 *
 * What we take, folder by folder: the archivists' proposed date, the title
 * (Grothendieck's own, or theirs in [brackets]), the announced leaf count, and
 * the rank in the hierarchy — read off the typographic indent, which is the
 * only thing distinguishing a sub-folder from a top-level one.
 *
 *   npm run catalogue
 */

import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const SOURCE = 'https://grothendieck.umontpellier.fr/archives-grothendieck/';
const OUT = resolve(import.meta.dirname, '..', 'src', 'content', 'catalogue.ts');

/**
 * The Montpellier server's certificate expired on 10 December 2025.
 *
 * That is no reason to give up: the certificate is genuinely the University of
 * Montpellier's, issued by GEANT, and it is its end date that has passed — not
 * its identity. But Node refuses the connection, so it has to be told
 * explicitly. The consequence is real and worth knowing: this exception holds
 * for the duration of the download, and it is also why the site cannot simply
 * frame the remote PDF — a browser would refuse with no way through.
 */
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const plain = (s) =>
  s
    .replace(/<sup>.*?<\/sup>/gs, '') // the inventory's footnote markers
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#8217;|&rsquo;/g, '’')
    .replace(/&laquo;|&raquo;/g, '"')
    .replace(/&[a-z]+;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

async function main() {
  process.stdout.write(`Reading ${SOURCE}\n`);
  const html = await (await fetch(SOURCE)).text();

  const start = html.indexOf('<div id="accordion"');
  if (start < 0) throw new Error('Inventory accordion not found: the page has changed.');
  const block = html.slice(start);

  // The two shapes of row, taken in document order: a group heading (div) and
  // a folder (a). A single scan preserves the inventory's order, which is
  // Grothendieck's own filing order.
  const row =
    /<div class="cotelink title twelve column row" data-target="([^"]*)">(.*?)<!--<div class="notes|<a class="cotelink twelve column row" href="#" data-target="([^"]*)" data-src="([^"]*)">(.*?)<\/a>/gs;

  const groups = [];
  const cotes = [];
  let current = null;

  for (const m of block.matchAll(row)) {
    if (m[1] !== undefined) {
      const date = plain(/class="date two wide column">(.*?)<\/div>/s.exec(m[2])?.[1] ?? '');
      const title = plain(/<span class="titre">(.*?)<\/span>/s.exec(m[2])?.[1] ?? '');
      current = { id: m[1], title, date, cotes: [] };
      groups.push(current);
    } else {
      const b = m[5];
      const date = plain(/class="date two wide column">(.*?)<\/div>/s.exec(b)?.[1] ?? '');
      const t = /<p class="ptitre" style="padding-left: (\d+)px">(.*?)<\/p>/s.exec(b);
      const count = plain(/class="nbpages two wide column">(.*?)<\/div>/s.exec(b)?.[1] ?? '');
      const id = m[3];
      cotes.push({
        id,
        // The file Montpellier serves carries the shelfmark verbatim.
        file: `${id}.pdf`,
        date,
        title: t ? plain(t[2]) : '',
        pages: Number(/\((\d+)\s*p\.?\)/.exec(count)?.[1] ?? 0),
        // 25 px = top level, 50 = folder inside a group, 75 = inside a subgroup.
        depth: t ? (Number(t[1]) - 25) / 25 : 0,
        group: current?.id ?? null,
      });
      current?.cotes.push(id);
    }
  }

  if (cotes.length < 150) throw new Error(`Only ${cotes.length} folders read: fix the parser.`);

  const total = cotes.reduce((s, c) => s + c.pages, 0);
  const header = `// Generated by \`npm run catalogue\` — do not edit by hand.
// Source: ${SOURCE}
// ${cotes.length} folders, ${groups.length} groups, ${total} leaves announced.

import type { ArchiveGroup, Cote } from '../lib/types.ts';

`;

  const body =
    `export const GROUPS: ArchiveGroup[] = ${JSON.stringify(groups, null, 2)};\n\n` +
    `export const COTES: Cote[] = ${JSON.stringify(cotes, null, 2)};\n\n` +
    `export const BY_ID = new Map(COTES.map((c) => [c.id, c]));\n`;

  await writeFile(OUT, header + body, 'utf8');
  process.stdout.write(`${cotes.length} folders, ${groups.length} groups, ${total} leaves → ${OUT}\n`);
}

main().catch((e) => {
  process.stderr.write(`${e.message}\n`);
  process.exit(1);
});
