#!/usr/bin/env node
/**
 * Builds the people network the Maps page draws: who is named together in
 * the same folder.
 *
 *   npm run people-network
 *
 * Reads src/content/people-evidence.json (letters, texts of theirs, and his
 * attributions, each with the file and line it rests on) and writes
 * src/content/people-network.json: nodes with fixed positions and a cluster,
 * and weighted links. Everything is computed here, once, so that the figure is
 * the same on every load and the site gains no dependency — the same choice as
 * the archive's mosaic.
 *
 * The method is the one VOSviewer uses for co-occurrence maps, cut down:
 *   - fractional counting: a folder naming n people gives each pair among them
 *     1/(n−1), so a folder that names twenty people does not outweigh twenty
 *     folders that each name two;
 *   - clusters by modularity (Louvain), deterministic: nodes visited in a fixed
 *     order, ties broken by index;
 *   - positions by a force layout (Fruchterman–Reingold) from a seeded start.
 * Nodes are the people who share a folder with at least one other person; a
 * person named alone in every folder they appear in has nothing to link to.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { layout, louvain, rankClusters } from './lib/network.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IN = resolve(ROOT, 'src/content/people-evidence.json');
const OUT = resolve(ROOT, 'src/content/people-network.json');

const { records } = JSON.parse(readFileSync(IN, 'utf8'));

// person → folders, folder → people
const byPerson = new Map();
const byFolder = new Map();
for (const r of records) {
  if (!byPerson.has(r.person)) byPerson.set(r.person, new Set());
  byPerson.get(r.person).add(r.folder);
  if (!byFolder.has(r.folder)) byFolder.set(r.folder, new Set());
  byFolder.get(r.folder).add(r.person);
}

// Fractional co-occurrence.
const pair = (a, b) => (a < b ? `${a}\u0000${b}` : `${b}\u0000${a}`);
const weight = new Map();
const sharedFolders = new Map();
for (const [folder, people] of byFolder) {
  const list = [...people].sort();
  if (list.length < 2) continue;
  const w = 1 / (list.length - 1);
  for (let i = 0; i < list.length; i++)
    for (let j = i + 1; j < list.length; j++) {
      const k = pair(list[i], list[j]);
      weight.set(k, (weight.get(k) ?? 0) + w);
      if (!sharedFolders.has(k)) sharedFolders.set(k, []);
      sharedFolders.get(k).push(folder);
    }
}

const names = [...new Set([...weight.keys()].flatMap((k) => k.split('\u0000')))].sort();
const idx = new Map(names.map((n, i) => [n, i]));
const N = names.length;
const links = [...weight].map(([k, w]) => {
  const [a, b] = k.split('\u0000');
  return { s: idx.get(a), t: idx.get(b), w, folders: sharedFolders.get(k) };
});

const W = 1000;
const H = 640;
const cluster = louvain(N, links);
const place = layout(N, links, { W, H });
const { rank, count } = rankClusters(cluster);
const out = {
  $why:
    'Generated by `npm run people-network` from people-evidence.json — do not edit by hand. Positions and clusters are computed once so the figure is the same on every load.',
  built: new Date().toISOString().slice(0, 10),
  width: W,
  height: H,
  nodes: names.map((n, i) => ({
    name: n,
    x: Math.round(place[i].x),
    y: Math.round(place[i].y),
    cluster: rank[i],
    folders: [...byPerson.get(n)].sort(),
  })),
  links: links.map((l) => ({ s: l.s, t: l.t, w: Number(l.w.toFixed(3)), folders: l.folders.sort() })),
};
writeFileSync(OUT, `${JSON.stringify(out, null, 1)}\n`);
process.stdout.write(
  `${out.nodes.length} people, ${out.links.length} links, ${count} clusters → src/content/people-network.json\n`,
);
